version: "3.9"

services:
  db:
    image: mariadb:10.0.33
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  backend:
    build:
      context: "./"
      target: "development"
    volumes:
      - "./:/app"
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - ".env"

volumes:
  db_data:
  redis_data:
