FROM golang:1.19.0 as development

WORKDIR "/app"
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/cosmtrek/air@v1.40.4

COPY . .

CMD ["air", "-c", "./config/.air.toml"]

FROM node:16.17.0 as node_tool

RUN npm install -g @apidevtools/swagger-cli@4.0.4
