version: "3.9"

services:
  db:
    image: mysql:8.0.28
    ports:
    - "${DB_PORT}:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  db_data:
