// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /activity/checkin)
	PostActivityCheckin(ctx echo.Context) error

	// (POST /activity/checkout)
	PostActivityCheckout(ctx echo.Context) error

	// (POST /activity/checkout/{userId})
	PostActivityCheckoutUserId(ctx echo.Context, userId string) error

	// (PUT /activity/record/{recordId})
	PutActivityRecordRecordId(ctx echo.Context, recordId string) error

	// (GET /budget)
	GetBudget(ctx echo.Context, params GetBudgetParams) error

	// (POST /budget)
	PostBudget(ctx echo.Context) error

	// (GET /budget/{budgetId})
	GetBudgetBudgetId(ctx echo.Context, budgetId string) error

	// (PUT /budget/{budgetId}/admin)
	PutBudgetBudgetIdAdmin(ctx echo.Context, budgetId string) error

	// (DELETE /budget/{budgetId}/status_approve)
	DeleteBudgetBudgetIdStatusApprove(ctx echo.Context, budgetId string) error

	// (PUT /budget/{budgetId}/status_approve)
	PutBudgetBudgetIdStatusApprove(ctx echo.Context, budgetId string) error

	// (PUT /budget/{budgetId}/status_bought)
	PutBudgetBudgetIdStatusBought(ctx echo.Context, budgetId string) error

	// (PUT /budget/{budgetId}/status_paid)
	PutBudgetBudgetIdStatusPaid(ctx echo.Context, budgetId string) error

	// (DELETE /budget/{budgetId}/status_pending)
	DeleteBudgetBudgetIdStatusPending(ctx echo.Context, budgetId string) error

	// (PUT /budget/{budgetId}/status_pending)
	PutBudgetBudgetIdStatusPending(ctx echo.Context, budgetId string) error

	// (GET /event)
	GetEvent(ctx echo.Context, params GetEventParams) error

	// (GET /event/{eventId})
	GetEventEventId(ctx echo.Context, eventId string) error

	// (GET /event/{eventId}/{reservationId})
	GetEventEventIdReservationId(ctx echo.Context, eventId string, reservationId string) error

	// (DELETE /event/{eventId}/{reservationId}/me)
	DeleteEventEventIdReservationIdMe(ctx echo.Context, eventId string, reservationId string) error

	// (PUT /event/{eventId}/{reservationId}/me)
	PutEventEventIdReservationIdMe(ctx echo.Context, eventId string, reservationId string) error

	// (GET /group)
	GetGroup(ctx echo.Context, params GetGroupParams) error

	// (POST /group)
	PostGroup(ctx echo.Context) error

	// (GET /group/{groupId})
	GetGroupGroupId(ctx echo.Context, groupId string) error

	// (POST /group/{groupId}/join)
	PostGroupGroupIdJoin(ctx echo.Context, groupId string) error

	// (POST /group/{groupId}/user)
	PostGroupGroupIdUser(ctx echo.Context, groupId string) error

	// (GET /login)
	GetLogin(ctx echo.Context) error

	// (POST /login/callback)
	PostLoginCallback(ctx echo.Context) error

	// (POST /mail)
	PostMail(ctx echo.Context) error

	// (POST /mattermost/create_user)
	PostMattermostCreateUser(ctx echo.Context) error

	// (GET /payment)
	GetPayment(ctx echo.Context, params GetPaymentParams) error

	// (GET /payment/{paymentId})
	GetPaymentPaymentId(ctx echo.Context, paymentId string) error

	// (PUT /payment/{paymentId})
	PutPaymentPaymentId(ctx echo.Context, paymentId string) error

	// (GET /signup)
	GetSignup(ctx echo.Context) error

	// (POST /signup/callback)
	PostSignupCallback(ctx echo.Context) error

	// (GET /status)
	GetStatus(ctx echo.Context) error

	// (GET /status/club_room)
	GetStatusClubRoom(ctx echo.Context) error

	// (PUT /status/club_room)
	PutStatusClubRoom(ctx echo.Context) error

	// (GET /storage/myfile)
	GetStorageMyfile(ctx echo.Context) error

	// (POST /storage/myfile)
	PostStorageMyfile(ctx echo.Context) error

	// (GET /storage/{fileId})
	GetStorageFileId(ctx echo.Context, fileId string) error

	// (GET /tool)
	GetTool(ctx echo.Context) error

	// (GET /user)
	GetUser(ctx echo.Context, params GetUserParams) error

	// (GET /user/me)
	GetUserMe(ctx echo.Context) error

	// (PUT /user/me)
	PutUserMe(ctx echo.Context) error

	// (GET /user/me/discord)
	GetUserMeDiscord(ctx echo.Context) error

	// (PUT /user/me/discord/callback)
	PutUserMeDiscordCallback(ctx echo.Context) error

	// (GET /user/me/introduction)
	GetUserMeIntroduction(ctx echo.Context) error

	// (PUT /user/me/introduction)
	PutUserMeIntroduction(ctx echo.Context) error

	// (GET /user/me/payment)
	GetUserMePayment(ctx echo.Context) error

	// (PUT /user/me/payment)
	PutUserMePayment(ctx echo.Context) error

	// (GET /user/me/private)
	GetUserMePrivate(ctx echo.Context) error

	// (PUT /user/me/private)
	PutUserMePrivate(ctx echo.Context) error

	// (PUT /user/me/renewal)
	PutUserMeRenewal(ctx echo.Context) error

	// (GET /user/search)
	GetUserSearch(ctx echo.Context, params GetUserSearchParams) error

	// (GET /user/{userId})
	GetUserUserId(ctx echo.Context, userId string) error

	// (GET /user/{userId}/group)
	GetUserUserIdGroup(ctx echo.Context, userId string) error

	// (GET /user/{userId}/introduction)
	GetUserUserIdIntroduction(ctx echo.Context, userId string) error

	// (GET /user/{userId}/work)
	GetUserUserIdWork(ctx echo.Context, userId string) error

	// (GET /work/tag)
	GetWorkTag(ctx echo.Context, params GetWorkTagParams) error

	// (POST /work/tag)
	PostWorkTag(ctx echo.Context) error

	// (DELETE /work/tag/{tagId})
	DeleteWorkTagTagId(ctx echo.Context, tagId string) error

	// (GET /work/tag/{tagId})
	GetWorkTagTagId(ctx echo.Context, tagId string) error

	// (PUT /work/tag/{tagId})
	PutWorkTagTagId(ctx echo.Context, tagId string) error

	// (GET /work/work)
	GetWorkWork(ctx echo.Context, params GetWorkWorkParams) error

	// (POST /work/work)
	PostWorkWork(ctx echo.Context) error

	// (DELETE /work/work/{workId})
	DeleteWorkWorkWorkId(ctx echo.Context, workId string) error

	// (GET /work/work/{workId})
	GetWorkWorkWorkId(ctx echo.Context, workId string) error

	// (PUT /work/work/{workId})
	PutWorkWorkWorkId(ctx echo.Context, workId string) error

	// (GET /work/work/{workId}/public)
	GetWorkWorkWorkIdPublic(ctx echo.Context, workId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostActivityCheckin converts echo context to params.
func (w *ServerInterfaceWrapper) PostActivityCheckin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostActivityCheckin(ctx)
	return err
}

// PostActivityCheckout converts echo context to params.
func (w *ServerInterfaceWrapper) PostActivityCheckout(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostActivityCheckout(ctx)
	return err
}

// PostActivityCheckoutUserId converts echo context to params.
func (w *ServerInterfaceWrapper) PostActivityCheckoutUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostActivityCheckoutUserId(ctx, userId)
	return err
}

// PutActivityRecordRecordId converts echo context to params.
func (w *ServerInterfaceWrapper) PutActivityRecordRecordId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "recordId", runtime.ParamLocationPath, ctx.Param("recordId"), &recordId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recordId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutActivityRecordRecordId(ctx, recordId)
	return err
}

// GetBudget converts echo context to params.
func (w *ServerInterfaceWrapper) GetBudget(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBudgetParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "proposerId" -------------

	err = runtime.BindQueryParameter("form", true, false, "proposerId", ctx.QueryParams(), &params.ProposerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter proposerId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBudget(ctx, params)
	return err
}

// PostBudget converts echo context to params.
func (w *ServerInterfaceWrapper) PostBudget(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostBudget(ctx)
	return err
}

// GetBudgetBudgetId converts echo context to params.
func (w *ServerInterfaceWrapper) GetBudgetBudgetId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetBudgetBudgetId(ctx, budgetId)
	return err
}

// PutBudgetBudgetIdAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) PutBudgetBudgetIdAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutBudgetBudgetIdAdmin(ctx, budgetId)
	return err
}

// DeleteBudgetBudgetIdStatusApprove converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBudgetBudgetIdStatusApprove(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteBudgetBudgetIdStatusApprove(ctx, budgetId)
	return err
}

// PutBudgetBudgetIdStatusApprove converts echo context to params.
func (w *ServerInterfaceWrapper) PutBudgetBudgetIdStatusApprove(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutBudgetBudgetIdStatusApprove(ctx, budgetId)
	return err
}

// PutBudgetBudgetIdStatusBought converts echo context to params.
func (w *ServerInterfaceWrapper) PutBudgetBudgetIdStatusBought(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutBudgetBudgetIdStatusBought(ctx, budgetId)
	return err
}

// PutBudgetBudgetIdStatusPaid converts echo context to params.
func (w *ServerInterfaceWrapper) PutBudgetBudgetIdStatusPaid(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutBudgetBudgetIdStatusPaid(ctx, budgetId)
	return err
}

// DeleteBudgetBudgetIdStatusPending converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBudgetBudgetIdStatusPending(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteBudgetBudgetIdStatusPending(ctx, budgetId)
	return err
}

// PutBudgetBudgetIdStatusPending converts echo context to params.
func (w *ServerInterfaceWrapper) PutBudgetBudgetIdStatusPending(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "budgetId" -------------
	var budgetId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "budgetId", runtime.ParamLocationPath, ctx.Param("budgetId"), &budgetId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter budgetId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutBudgetBudgetIdStatusPending(ctx, budgetId)
	return err
}

// GetEvent converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvent(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEvent(ctx, params)
	return err
}

// GetEventEventId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventEventId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventId", runtime.ParamLocationPath, ctx.Param("eventId"), &eventId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventEventId(ctx, eventId)
	return err
}

// GetEventEventIdReservationId converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventEventIdReservationId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventId", runtime.ParamLocationPath, ctx.Param("eventId"), &eventId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventId: %s", err))
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "reservationId", runtime.ParamLocationPath, ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventEventIdReservationId(ctx, eventId, reservationId)
	return err
}

// DeleteEventEventIdReservationIdMe converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventEventIdReservationIdMe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventId", runtime.ParamLocationPath, ctx.Param("eventId"), &eventId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventId: %s", err))
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "reservationId", runtime.ParamLocationPath, ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteEventEventIdReservationIdMe(ctx, eventId, reservationId)
	return err
}

// PutEventEventIdReservationIdMe converts echo context to params.
func (w *ServerInterfaceWrapper) PutEventEventIdReservationIdMe(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "eventId", runtime.ParamLocationPath, ctx.Param("eventId"), &eventId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventId: %s", err))
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "reservationId", runtime.ParamLocationPath, ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutEventEventIdReservationIdMe(ctx, eventId, reservationId)
	return err
}

// GetGroup converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroup(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "seed" -------------

	err = runtime.BindQueryParameter("form", true, false, "seed", ctx.QueryParams(), &params.Seed)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter seed: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGroup(ctx, params)
	return err
}

// PostGroup converts echo context to params.
func (w *ServerInterfaceWrapper) PostGroup(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostGroup(ctx)
	return err
}

// GetGroupGroupId converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroupGroupId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "groupId", runtime.ParamLocationPath, ctx.Param("groupId"), &groupId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGroupGroupId(ctx, groupId)
	return err
}

// PostGroupGroupIdJoin converts echo context to params.
func (w *ServerInterfaceWrapper) PostGroupGroupIdJoin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "groupId", runtime.ParamLocationPath, ctx.Param("groupId"), &groupId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostGroupGroupIdJoin(ctx, groupId)
	return err
}

// PostGroupGroupIdUser converts echo context to params.
func (w *ServerInterfaceWrapper) PostGroupGroupIdUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "groupId", runtime.ParamLocationPath, ctx.Param("groupId"), &groupId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostGroupGroupIdUser(ctx, groupId)
	return err
}

// GetLogin converts echo context to params.
func (w *ServerInterfaceWrapper) GetLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetLogin(ctx)
	return err
}

// PostLoginCallback converts echo context to params.
func (w *ServerInterfaceWrapper) PostLoginCallback(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostLoginCallback(ctx)
	return err
}

// PostMail converts echo context to params.
func (w *ServerInterfaceWrapper) PostMail(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostMail(ctx)
	return err
}

// PostMattermostCreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) PostMattermostCreateUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostMattermostCreateUser(ctx)
	return err
}

// GetPayment converts echo context to params.
func (w *ServerInterfaceWrapper) GetPayment(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"account"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPaymentParams
	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameter("form", true, false, "year", ctx.QueryParams(), &params.Year)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter year: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPayment(ctx, params)
	return err
}

// GetPaymentPaymentId converts echo context to params.
func (w *ServerInterfaceWrapper) GetPaymentPaymentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "paymentId" -------------
	var paymentId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "paymentId", runtime.ParamLocationPath, ctx.Param("paymentId"), &paymentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter paymentId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"account"})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPaymentPaymentId(ctx, paymentId)
	return err
}

// PutPaymentPaymentId converts echo context to params.
func (w *ServerInterfaceWrapper) PutPaymentPaymentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "paymentId" -------------
	var paymentId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "paymentId", runtime.ParamLocationPath, ctx.Param("paymentId"), &paymentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter paymentId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"account"})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutPaymentPaymentId(ctx, paymentId)
	return err
}

// GetSignup converts echo context to params.
func (w *ServerInterfaceWrapper) GetSignup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSignup(ctx)
	return err
}

// PostSignupCallback converts echo context to params.
func (w *ServerInterfaceWrapper) PostSignupCallback(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostSignupCallback(ctx)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// GetStatusClubRoom converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatusClubRoom(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetStatusClubRoom(ctx)
	return err
}

// PutStatusClubRoom converts echo context to params.
func (w *ServerInterfaceWrapper) PutStatusClubRoom(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutStatusClubRoom(ctx)
	return err
}

// GetStorageMyfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetStorageMyfile(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetStorageMyfile(ctx)
	return err
}

// PostStorageMyfile converts echo context to params.
func (w *ServerInterfaceWrapper) PostStorageMyfile(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostStorageMyfile(ctx)
	return err
}

// GetStorageFileId converts echo context to params.
func (w *ServerInterfaceWrapper) GetStorageFileId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileId" -------------
	var fileId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "fileId", runtime.ParamLocationPath, ctx.Param("fileId"), &fileId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetStorageFileId(ctx, fileId)
	return err
}

// GetTool converts echo context to params.
func (w *ServerInterfaceWrapper) GetTool(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTool(ctx)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "seed" -------------

	err = runtime.BindQueryParameter("form", true, false, "seed", ctx.QueryParams(), &params.Seed)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter seed: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, params)
	return err
}

// GetUserMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserMe(ctx)
	return err
}

// PutUserMe converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutUserMe(ctx)
	return err
}

// GetUserMeDiscord converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserMeDiscord(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserMeDiscord(ctx)
	return err
}

// PutUserMeDiscordCallback converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserMeDiscordCallback(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutUserMeDiscordCallback(ctx)
	return err
}

// GetUserMeIntroduction converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserMeIntroduction(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserMeIntroduction(ctx)
	return err
}

// PutUserMeIntroduction converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserMeIntroduction(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutUserMeIntroduction(ctx)
	return err
}

// GetUserMePayment converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserMePayment(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserMePayment(ctx)
	return err
}

// PutUserMePayment converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserMePayment(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutUserMePayment(ctx)
	return err
}

// GetUserMePrivate converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserMePrivate(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserMePrivate(ctx)
	return err
}

// PutUserMePrivate converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserMePrivate(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutUserMePrivate(ctx)
	return err
}

// PutUserMeRenewal converts echo context to params.
func (w *ServerInterfaceWrapper) PutUserMeRenewal(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutUserMeRenewal(ctx)
	return err
}

// GetUserSearch converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserSearch(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserSearchParams
	// ------------- Required query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, true, "query", ctx.QueryParams(), &params.Query)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter query: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserSearch(ctx, params)
	return err
}

// GetUserUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserUserId(ctx, userId)
	return err
}

// GetUserUserIdGroup converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserUserIdGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserUserIdGroup(ctx, userId)
	return err
}

// GetUserUserIdIntroduction converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserUserIdIntroduction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserUserIdIntroduction(ctx, userId)
	return err
}

// GetUserUserIdWork converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserUserIdWork(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserUserIdWork(ctx, userId)
	return err
}

// GetWorkTag converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkTag(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkTagParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWorkTag(ctx, params)
	return err
}

// PostWorkTag converts echo context to params.
func (w *ServerInterfaceWrapper) PostWorkTag(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostWorkTag(ctx)
	return err
}

// DeleteWorkTagTagId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorkTagTagId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tagId" -------------
	var tagId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "tagId", runtime.ParamLocationPath, ctx.Param("tagId"), &tagId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tagId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteWorkTagTagId(ctx, tagId)
	return err
}

// GetWorkTagTagId converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkTagTagId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tagId" -------------
	var tagId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "tagId", runtime.ParamLocationPath, ctx.Param("tagId"), &tagId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tagId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWorkTagTagId(ctx, tagId)
	return err
}

// PutWorkTagTagId converts echo context to params.
func (w *ServerInterfaceWrapper) PutWorkTagTagId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tagId" -------------
	var tagId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "tagId", runtime.ParamLocationPath, ctx.Param("tagId"), &tagId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tagId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutWorkTagTagId(ctx, tagId)
	return err
}

// GetWorkWork converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkWork(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkWorkParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "authorId" -------------

	err = runtime.BindQueryParameter("form", true, false, "authorId", ctx.QueryParams(), &params.AuthorId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter authorId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWorkWork(ctx, params)
	return err
}

// PostWorkWork converts echo context to params.
func (w *ServerInterfaceWrapper) PostWorkWork(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostWorkWork(ctx)
	return err
}

// DeleteWorkWorkWorkId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorkWorkWorkId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "workId", runtime.ParamLocationPath, ctx.Param("workId"), &workId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteWorkWorkWorkId(ctx, workId)
	return err
}

// GetWorkWorkWorkId converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkWorkWorkId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "workId", runtime.ParamLocationPath, ctx.Param("workId"), &workId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWorkWorkWorkId(ctx, workId)
	return err
}

// PutWorkWorkWorkId converts echo context to params.
func (w *ServerInterfaceWrapper) PutWorkWorkWorkId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "workId", runtime.ParamLocationPath, ctx.Param("workId"), &workId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutWorkWorkWorkId(ctx, workId)
	return err
}

// GetWorkWorkWorkIdPublic converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorkWorkWorkIdPublic(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "workId" -------------
	var workId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "workId", runtime.ParamLocationPath, ctx.Param("workId"), &workId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter workId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWorkWorkWorkIdPublic(ctx, workId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/activity/checkin", wrapper.PostActivityCheckin)
	router.POST(baseURL+"/activity/checkout", wrapper.PostActivityCheckout)
	router.POST(baseURL+"/activity/checkout/:userId", wrapper.PostActivityCheckoutUserId)
	router.PUT(baseURL+"/activity/record/:recordId", wrapper.PutActivityRecordRecordId)
	router.GET(baseURL+"/budget", wrapper.GetBudget)
	router.POST(baseURL+"/budget", wrapper.PostBudget)
	router.GET(baseURL+"/budget/:budgetId", wrapper.GetBudgetBudgetId)
	router.PUT(baseURL+"/budget/:budgetId/admin", wrapper.PutBudgetBudgetIdAdmin)
	router.DELETE(baseURL+"/budget/:budgetId/status_approve", wrapper.DeleteBudgetBudgetIdStatusApprove)
	router.PUT(baseURL+"/budget/:budgetId/status_approve", wrapper.PutBudgetBudgetIdStatusApprove)
	router.PUT(baseURL+"/budget/:budgetId/status_bought", wrapper.PutBudgetBudgetIdStatusBought)
	router.PUT(baseURL+"/budget/:budgetId/status_paid", wrapper.PutBudgetBudgetIdStatusPaid)
	router.DELETE(baseURL+"/budget/:budgetId/status_pending", wrapper.DeleteBudgetBudgetIdStatusPending)
	router.PUT(baseURL+"/budget/:budgetId/status_pending", wrapper.PutBudgetBudgetIdStatusPending)
	router.GET(baseURL+"/event", wrapper.GetEvent)
	router.GET(baseURL+"/event/:eventId", wrapper.GetEventEventId)
	router.GET(baseURL+"/event/:eventId/:reservationId", wrapper.GetEventEventIdReservationId)
	router.DELETE(baseURL+"/event/:eventId/:reservationId/me", wrapper.DeleteEventEventIdReservationIdMe)
	router.PUT(baseURL+"/event/:eventId/:reservationId/me", wrapper.PutEventEventIdReservationIdMe)
	router.GET(baseURL+"/group", wrapper.GetGroup)
	router.POST(baseURL+"/group", wrapper.PostGroup)
	router.GET(baseURL+"/group/:groupId", wrapper.GetGroupGroupId)
	router.POST(baseURL+"/group/:groupId/join", wrapper.PostGroupGroupIdJoin)
	router.POST(baseURL+"/group/:groupId/user", wrapper.PostGroupGroupIdUser)
	router.GET(baseURL+"/login", wrapper.GetLogin)
	router.POST(baseURL+"/login/callback", wrapper.PostLoginCallback)
	router.POST(baseURL+"/mail", wrapper.PostMail)
	router.POST(baseURL+"/mattermost/create_user", wrapper.PostMattermostCreateUser)
	router.GET(baseURL+"/payment", wrapper.GetPayment)
	router.GET(baseURL+"/payment/:paymentId", wrapper.GetPaymentPaymentId)
	router.PUT(baseURL+"/payment/:paymentId", wrapper.PutPaymentPaymentId)
	router.GET(baseURL+"/signup", wrapper.GetSignup)
	router.POST(baseURL+"/signup/callback", wrapper.PostSignupCallback)
	router.GET(baseURL+"/status", wrapper.GetStatus)
	router.GET(baseURL+"/status/club_room", wrapper.GetStatusClubRoom)
	router.PUT(baseURL+"/status/club_room", wrapper.PutStatusClubRoom)
	router.GET(baseURL+"/storage/myfile", wrapper.GetStorageMyfile)
	router.POST(baseURL+"/storage/myfile", wrapper.PostStorageMyfile)
	router.GET(baseURL+"/storage/:fileId", wrapper.GetStorageFileId)
	router.GET(baseURL+"/tool", wrapper.GetTool)
	router.GET(baseURL+"/user", wrapper.GetUser)
	router.GET(baseURL+"/user/me", wrapper.GetUserMe)
	router.PUT(baseURL+"/user/me", wrapper.PutUserMe)
	router.GET(baseURL+"/user/me/discord", wrapper.GetUserMeDiscord)
	router.PUT(baseURL+"/user/me/discord/callback", wrapper.PutUserMeDiscordCallback)
	router.GET(baseURL+"/user/me/introduction", wrapper.GetUserMeIntroduction)
	router.PUT(baseURL+"/user/me/introduction", wrapper.PutUserMeIntroduction)
	router.GET(baseURL+"/user/me/payment", wrapper.GetUserMePayment)
	router.PUT(baseURL+"/user/me/payment", wrapper.PutUserMePayment)
	router.GET(baseURL+"/user/me/private", wrapper.GetUserMePrivate)
	router.PUT(baseURL+"/user/me/private", wrapper.PutUserMePrivate)
	router.PUT(baseURL+"/user/me/renewal", wrapper.PutUserMeRenewal)
	router.GET(baseURL+"/user/search", wrapper.GetUserSearch)
	router.GET(baseURL+"/user/:userId", wrapper.GetUserUserId)
	router.GET(baseURL+"/user/:userId/group", wrapper.GetUserUserIdGroup)
	router.GET(baseURL+"/user/:userId/introduction", wrapper.GetUserUserIdIntroduction)
	router.GET(baseURL+"/user/:userId/work", wrapper.GetUserUserIdWork)
	router.GET(baseURL+"/work/tag", wrapper.GetWorkTag)
	router.POST(baseURL+"/work/tag", wrapper.PostWorkTag)
	router.DELETE(baseURL+"/work/tag/:tagId", wrapper.DeleteWorkTagTagId)
	router.GET(baseURL+"/work/tag/:tagId", wrapper.GetWorkTagTagId)
	router.PUT(baseURL+"/work/tag/:tagId", wrapper.PutWorkTagTagId)
	router.GET(baseURL+"/work/work", wrapper.GetWorkWork)
	router.POST(baseURL+"/work/work", wrapper.PostWorkWork)
	router.DELETE(baseURL+"/work/work/:workId", wrapper.DeleteWorkWorkWorkId)
	router.GET(baseURL+"/work/work/:workId", wrapper.GetWorkWorkWorkId)
	router.PUT(baseURL+"/work/work/:workId", wrapper.PutWorkWorkWorkId)
	router.GET(baseURL+"/work/work/:workId/public", wrapper.GetWorkWorkWorkIdPublic)

}
