// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PcxpX+KyjsVsWugjyUZWezqsqDLpbDRLRZpJQ8uFQqcNAcQsQAY1xIMaypEmci",
	"h7KsSJvEVhS7dqP4ElmyKHvljS+SrR8DDUk95S9soS9AA+hu9GAGw+GID5ZJAug+l69Pnz59us+6Wnea",
	"LccGtu+pR9dVF3gtx/YA/OW4bsyBtwPg+dFvdcf2gQ1/1Fsty6zrvunYtQueY0d/8+pLoKlHP/27CxbV",
	"o+q/1ZKma+ipV3vNdR1XbbfbmmoAr+6aragR9aj6a90yDdiiAqJ3NAX49ZfUtqYet3R7eT6o14HnDY0O",
	"0h6DEvxIIaKIaJi2feDaujUP3BXgVi+N+TXPB82sJN5w/FNOYBvV9z8HPCdw60AxHOAptuMr4KLp+Qkp",
	"Z2098Jcc1/wtGAE5xwJ/Cdg+bjUtlraGW4fgQE0cXVdbrtMCrm8iJFtgBVjRD/5aC6hHVc93TbsRMdIE",
	"nqc3AONZW1Nd8HZguhGHb+Emkg/OtTV1Drw963j+sbpvrpj+2oklUF827Xz3LUuvwy6a+sXTwG74S+rR",
	"I1Oa2jTt+Fct07+mXjzk6C3zUN0xQAPYh8BF39UP+XoDNnlBV4+qvb99vX3lUu/GNVVTV9AAilogZGtN",
	"0/75Ea2pX/z5kSkkV5ojRBWPDyfw84zU8ZPzOny46LjN6Cc16viQbzaBWoaNsLsRdv4Rdrth50HY+XvY",
	"+Szsbm7f6vQ2H6UZc5qmD5otfw1qZ59I9XhgNABLlpaODFoJCjffeXb7vzOysYGz+PNF4Pnmim4pi+ZF",
	"YCgt17kA6r7iBL5nGkBxHacJZWfrTVCy7xvXelc4oslLA/ajYV4poby2Amz0D0MwugVsQ3fPr5hglSJy",
	"wXEsoNtykOrcC7tfhN2HYfdS2H28e/vOziffc4nO2Jt1GkKHy0Bo9+4X23/5gwA/h1NaGLS7sPNJ2L0F",
	"ud0U4/YwV0W0BLSMDijFve46QSuvs4z8yrDwZdi9F3Yfh92b4cZWsQDhADw8NTUFJXnBMW19wQIl4dK7",
	"3um9+7fe9Qe73R/C7vth9/Ow8+WAA4XmqEApkJeXX31VUjkxs1m9HDOarOmnbulmcxhquff00V+efvuH",
	"cONW2LkKWxUwFrOkHaBjT9ChYcVnUQL/mTbOeoDhKQUecKeNkjx1P4sY6vwz7D6ePslhKQhMxjyBu6VI",
	"Pe00TPuEblkLen2ZgWnHKCn53bvXdu88DjsPofCvyM5ksEOKvhndtPJk6YbhAg+vnyJnxUv5SaAZfaXl",
	"3VD8B9119TUpLp5d2nj65Hbv8mbkMHWvRJNd5zuOt6QZ5grQUN8RWwuOsVZOdtsffbH9we8F86gHbOOM",
	"E9shAyzqgeWrRxd1ywNamcG3s3V758Y7u5cu7/z5Ds1ruHEv7HSQGFDXwULk65Qdjk/gJLoZdu8J2EMw",
	"5SgXInu4uhUMqLR283gl4sDqTiHX94HbdDz/hAt0HwRMQ2Cb9eUBzFv3Kvbnu9fgOPtboTP98svIq9c9",
	"b9VxS5ug/4qw0X0gGtyw05/BTn/6SqzXQZhN1CSzbICcMgwgNuex5ClhUOqbNxt20BpjyzjvO67eADNr",
	"iyaactP0kb+WkfP7Yec2HKf3BF7H4alXfvbqf/wUz/2mNxssWGa97Nx/+YtnH1xN9WYHljXg5E8xIuNB",
	"sad9KEiKQUoF0dw+A153dQOcbaF2s2pwge6Vdcd2/vxw997VnRvv7Pz5K1mU4P4oIn/juMtn9EYFiwmR",
	"fziw3/Yk7HzJVZqUj5aRQfQfw5OA8bX0VDP41PL0h492L11O0w69A+yWaSMQfoTbYfPFNw1p7sor/ukP",
	"H/X+tCFSvKaSD4bJGMQbnyWZFQGBEhE9JpTAMIgDf3Og7rgG+hctAjKYxO+dR2ysq8AOmnAKwJFPLY4Q",
	"qufKBTL+Dn2Gd8LOx2H3T/gH7JvdRDI2kQaHFHvc/vDr7Q++xMHGnDjTDOPOKblFfi5lZakfWeLzfN0P",
	"vLJ257tIGpGb8STn6cdTBgoC6q2W66wAQ3FB5AKyrBImJWEFRSnRv9MGJ5BQGQOIbkSugslXWrrZP+Xz",
	"8PEx1ESegwUnaCz5JX2B3YePe5c/3f52M9x4sueWzAVNHc0bJWK4nVu7l7p4web7FmjiQCxuyrR90ACu",
	"3AD66vudrZsMPSUNx8RqRP5EdGItHo+VlfcgD8Tej9hlpD0bDTeGmzgEfnOuIGyzgBxgG1FH+SEc76eU",
	"ENvT7zcjsY2nc9KMF+ZnXaucyJO1/fa77+/ceXJ27nS1+z2a2grcluOVbH3nw62dv/5O0HoV+MNOEgZS",
	"wkFWA4IBlOxfTRtzwAPuCtyanjZmAGtF3iQjffCdnodh9zba6UlLLRsq1tQAgWjQLiMICXvKhQOa2PxE",
	"BCQim9XXor/j/7H8I+g7AqPslh+1i4ww7/hguMAhBOK2E96QyTphBQtzjtNk5B849eXSbN1HPO28+8/t",
	"y1eRD+wsA3ugGE93E3piD2RXsZAB0nHCN4oz5Pk1645d2obBRcAnEOkPc+Djbo3ANBDHsaAPXnJ26N3/",
	"rPfd14Ud/ifqbslx/Wnbdx0jqJdfLu/8z/1w43e7v7/b++arna+/e/roqjTDo4paCgY7FbYkOk8rgiWn",
	"LH5Oml604hzXkCYhM6vrDOQHRgIXAyjgmCHRFEkUG9k8lb6r294icN8oDZvt9x7s/hgBZufHz8thJkVD",
	"jnLXXGHGK/HOWtngzfXtK5ekB9ai6Xr+G5W4TKLefqXb+iA9vgCzXt59Ubpn05vRS++Kb1/6R2/zU2Zk",
	"3NIHFd/9m9JMkM4Gk979m31Lr6W7wPaPDYLLnW/e3b706bNLH+/83+3e5c0+YYoIOAEsq7Xk2OCNoLmA",
	"dvIGJmT7xve9bx88+/DR7udf7bx/t3f9Gw5RsGMbdZyQdGqw8ZMhJtzYYo2oZAOUJ5lfOE0wbMn0Pvy+",
	"t/VXvmQSqtiiOa0PXzLZwSKUzKDy6BsUWU+SCCAzcmmrm7WJsaVK06/FkwJvLGQHaTLb4M2nM3qDtRJ5",
	"XnaggngDKvqPGfI/2IY62IYawTaU9zqIt6FmLb0O4D8nAtdl+rHRuiPNo+hgQUHzb8JMGZgPl5UNa70j",
	"RTLVJi/OMW0fk82ib2v8JbXcUjROXuI+YmOSk6in0Su/fPf0apDmViS4X5ie77hrVekaNz9UXefbZOt6",
	"2j7hBMxQ/75XLGEtL6ZIHmdho2hD2WOExcymyZGKs7joAc4zN2mvBCRydCH1oV/yoNBU3/F1i0VJblsD",
	"kUW+iJnQMKMSMkrRMhzDgT96M/AFX0UrN5Qh7bsBYJkf2/RN3TpRynSlvh2QkPjUT+6JS+UtiLEev0ma",
	"S1spJreU8jK7/nk9NZKHfaM00zgCBN1bkdlKdc6nOt9wHm4wPdQ45jPFDfs5aS4usgdpI5sLwdAXOwMt",
	"snucRIPIosEmeUQNxRSmSdeYpjHhPmYkJlujJEcTnCiDdyYMbUn1ixnUGlIobrkIJKSjLElkD5axEMBJ",
	"JRzB48duPxSTzhDlx0gLbY2/xxs/4yiZc6iurRWAOb8YKMfEKdMCrDmkYGuXuySIDJ7rtBxvEMnOkhZE",
	"u7WCvdaifIXyA5aJSjjUUgcHqZEVS4Pav03lPEhs5sZYTVYi9IClkC4avRz0yu+FVem5kU7FRJ/iJmhz",
	"iJIjCDeAXxeTMEuhe4zlljKu8ikp5c3VUM0BTT36uUWZhJGP7dlkDPOGeWpIxwOdPxgFHI4rsDinn8EK",
	"uYujj6kItoX4Rs0Wzf+4lww1OKGFfyT71+wT2UXxuraGOuzPqkQUw8wa9snN5LnPzBmhnpuOXUqiWB5k",
	"URY3Jideeh5jn66G4kyxmeIpwwBbWXniGNpr6XXTX2MP7yLNLZq26S2d1H22jhZdAE4IOxiFek+JiXTp",
	"FK2iN+Z93fW5TXmCp7llJt0rBwtJeylRS6LiFOOLNA9aov6Msth4msuKaphYElmBA5xJ40wrFRPlarmP",
	"mGhi2KTAzcdwEewHBbeWC9/KsC9K3RSvKNMXFtG5VeHG1s6tR8/e+9/tm59u3+pEhEpFzbhwDkS+S73f",
	"GLHId4GtJU5aKrGT5j8jZNoRmQxXopLpPZEa51KVRvTnfkc5bIsE96Jmi+OFsJcMNfiSiD63xmHcL/4w",
	"Hwj2cBQSs5tXg+CmDvyUZ6T5w8UDrmD7pYwlpSXUh/EkouHAJiE0dYkHZjojvbx94xCVP9gvElR19iND",
	"KI1QNvD3DYaKtNyXXhMxwQtQGLuhTOuf1UJqpcnNBm2hB/3CH7eHAzi48SLwx33l6Eq308epAG6OP8y2",
	"oo4ZMJyrwAC2z8uDingRJsr2MSASQqiNhHT/md5SpwsoOQlOTkymGJjHLSKBoCswhjI25uPgVsFRV54v",
	"kDqPmrTY91kQ5okLulV4qcapODbbz1YduOgD2+Mv8LnxXsHlGW1NXZ43fwv6c8MKdu/6jcrxAs8xwrAJ",
	"RpTSgqB4423XaTmoFN5r0q8lTTUp2kFiMOrxSBPF9icEJ3uCh0TcZxyHcfeXgY6xnJUxQtS7SbP8G9n6",
	"xVXU0gCZTrxjXfA6BHA6k7WT6IVwxQ+ii2Lv2A9iY0h8uEs6Vap4xqsumSoz2fHOS6WFyE7CohWRCC6r",
	"QHyuaijzpMSNQgNkveRaH1rai0TL+z/vpSB/ZbBclcEPv0kcXUs64q4DlmCypVkSW6m1Bkk1LcJU0iWH",
	"ynRz/S1dil1r4Ry4BnRXYjUKXxN41nyN938ST3xyrvikm+hEmvBUWeEpsOLTWvLHqWROOckfQZI4GFR0",
	"amekJ2xOJ41npVB0CCcrC/bhHIb70tcO/pAchercgNRkTzkBnGPSRB6JUzVKn+zA7eK5XSztjGCS5F6a",
	"mDv0Uzwz4rbQSIsaLZoPM+d1ct/Lx5p9cu5OLAT0Wi6CPMDhPdGiswxRrHN1hET2xY6rjrtcRlPRf0jU",
	"sN0iXaFu8gRRTUgd9itDHE6JhK2xsmGLU05cLw5gZE8EVJusGBProOuTC/AyLFkxR58GlSgDSfweZ2Mp",
	"ESd9CI8xmAVaHNcsOpFAR2mO+j1DKw8V1OrgQ6r/6CSLAl6CexWDhO630gFSeDJVoItxHxg55Y0u35un",
	"x70Zl0mEejxHp2DVbIG+T43sr2FHD7e9Kw81zHsH2iRR6Ty6VVNcJaLfIk/TJwe+RCJdMarNTHE6bxbm",
	"OOECUQy3CauyTMGogjQicYJHNUkc3Bo7SavnMkzjXJxfOqw0Dum6g+l6g55cFZ9BWi8ovHNhVSICHb1E",
	"NcmulbOom1bgZrwS+VAjIKUexaQkASz0wTmGOfNQyU9ZcKRe1xI+UhzL1Fjpb86nZzeZQiB9aYoqsJpJ",
	"hEgeFGVC4DfPoQuO64Fr+mvz0RSDy8kC3QVuNEnCM1Pwt1PELP7yN2dUXMkT9gGfJnZyyfdbyEiZ9qID",
	"iTH9yAKoJ82GWXfcaCiuABdtXqtHXjr80hS8RqAFbL1lwj9NvXQExhz9JUhOjVzuXqtTdTsdj5HOS47r",
	"K8k995GI4jxvlVUFFAkHeP5xXG5pKDVSOSVHWUVTM0QrmByV1lq0pEbZr0nZ35enpnhUxO/VUlV525r6",
	"itRHSUFh+MmR4k9ShWbbmvqqTD+Zcr00HtWjb6WR+Na59jniLiUX/iMQZyBCSqJKYCR6tRAk6KVRoSTq",
	"rRAmTuBPBk5emXql+KO4oPLeA6u2jpZ1bQHCjKZpK4uOWweKXgptcXC7pbt6E/gwseStdTWyfdAwEn/n",
	"aLLITGNAowCYnVjOHWB5YrEcTbuurkpBGl6pUluH/2vX6skVXviMdFpnrwNfwe8oMA9JMW2F3MqShrTw",
	"ijAZUJNm+8R0HidDArb40jNBbfpGVmj7bT5NY2QpSaDgYgS+qqyYnukr5H0pgPwifrkKgGi4nbcDAPsg",
	"DQHXdMTmk9ROMuAVfKsALKua2nRsfylfO4nbj0EOx/F6SZ01yx8z2xOAx+k3YoAjjS8luToT7mOiW6lq",
	"6+R2KuQKBIzxgHK7EicAfaH4ZhMGrzOOALe+l8yIoK7KGgtPgMuMyB3A8kG5Tgc+wShBHc1OsW9bo27u",
	"4xr66N0stD2Rqc9fNFiRg8uz9XjS6PvD+HrA5Mu4YPKUpjZN22xGc8SUxohIsZu0cEowo8VXoyb1i6jJ",
	"w1N0B4cZHYxuYsjrr2BigAghwNgnRj5au9VgIu6hIE47Zo6B7StPdu9e6/14Ody4jQqS7H780fb9j1HR",
	"1affXtr97B/hxlbv+ge9H2/+6/EmXSD7X4+vMEdK9sbC6nWb7bForkfVvhQooYyhHicds9ZBKa3y1F1b",
	"T2Vl8+f2vMrDjS2EiVrv2tdPv70qofPC2pQyFjKbRj4u87+QMQbOUsILu3fDzoOwcwfWo9w8cAJGMyCS",
	"G9K48z56RbFMz2fZsONxtTYGcIsnVtkJlFwbhnJA9zAuQC7y5NtNWmCT4kZinJxra5wgKNpOU+Ir4fJB",
	"zxgoFQYj+cpJ9V5oVoaOl/j+VgFu8Oy6EN8UOyHr6hg7icGprZNrB9sStodvdo4nlxcWz5vUTYfjFGiU",
	"B0gjkcjE2RUmNpC/VhRuwfZ2YU3R63UnsH3FdSzA8r1YxbSrRU5VzhaLkwOrt9eLEIw/tR+Io/Oe5/Wk",
	"MroBLOCDPNxPwr9jSb2AviNF2V/MwR29LSrCPmqb2Z+vPkKHptC2FAq7oNz9JNiYNEcHtmb/eFjExCwk",
	"ZfulEY++kQb8cdTF5OAdM3QA9/0H95aOMrzlwR59IQ31Wd00JgjokJ0DmO9DmKMIfd+OI/6uH8dxFnd1",
	"4Dj26zhyhc0bjSOR9EjtC+bowMSMrYkBK0X5gPAN7k4AOhc2tI2A6iNvuCSHOOBG8TwpQTekaH4sf9bx",
	"MN/MQD7Rc4VxfOqcIUM9eK8BUHSMzGz0Sd2kQSa2E7V1fNl6u9hicI3Fa/F97cXTHF3hYHyC9yk2ZCzJ",
	"JBoRgRvEsSLBCPW/R0YqI4AxM1IZx4aC5vOZJimwb7X1VEkVCXunUB8U2b65TLmWagaCxskhTvc9roY1",
	"LSMpf81NFwV73jBaa8rsJDXXJPCK3uWqYwYcgHYw0BoCZTwnzgJ2maXwmPEd9jUYqwrAiATEQOIMW+6j",
	"DseUGj11AXQm0fA3yLUtXBcEvsEN0pAqRdVma3oAGHsd3cFVtsTeAiWsSUFLI65XJMzUtMEq4p4Z4yEw",
	"qXD5ROln5IujQmxgs9IgldomJN5LsBFbEirDTgosyqrpLym6vabULd1svqTANPPtO58/u3Uj7Pxx+72N",
	"cOOTdJXF954+erT9u+vhxhb8JNzYCjtfht170cPuzbDzx6c/fLS9eaN3/cFu9wc+GEm2XtWIpHLpxhaW",
	"UGmTAE72KYUsRtfxrV9tiXnPNH7iKS3XWTQtwJ3/Xo9vEZM5bUPeHaeVRooNqTkuJZhJm+sYWKldcESG",
	"7ZeOaSu+UzQF0nfF7VO0MHkRQOZCSjLPcUxQBK743jjOjUAGOgwrDTB4XWClAKt21qTZ2MO5M0cGG+J6",
	"Tj8HMIcwt0htU+4sC99Qzs6dZk2uqDRq5ZMf6oah39Mxce02deQ7Yprir1anr2ZkDuBfA9dcXFPgl6yh",
	"m76Ls9Lhle6KdZtG4C9Fbji8UGYPIjdSRJKR56EKoQOgmqHVJrnGlKnLeWAbykJgLSsAvsjS5wx6UKEa",
	"YQ8MwbwW0dTv1SfDVB2PsFhjkfiQ5CZuqQG5IhgiF8PW0CLrvHiKJyHr+DNy+IyDr/S1s3i6rxRvjItu",
	"WbFfFgN7AEI5agkofScO/Obpn5xwTcIcRmkrKcLHv5ANvcONAJNCflIxYFymbk8DuXEl84KrSmi+9/PN",
	"DcxThETzKRzU1uPy3e3iu5taseJ5mJilioFLXMpHvT1OsZEcM6KA2hKoL6fFM4FHUBPw8DZg82Jg7LuO",
	"GiVVbY/KAIQpkVHviB4gWWwG8WpCZPnQK7wFK7qqv/oVK+6Hpb6EPs7qBnEwhEVrpi5Bpe5npq8xXbYW",
	"U1npujWpKs2EL/pYwUeI4PhmYpgUjK4aw6gfliotS5lf83zQ9JQ3CXm6NQxpYRHR8qrVrWDhvOs4TfHd",
	"1VawoERvKXFFbY7oTljBwlzU3IhEGPdXdJF0hgOlpTf2wdZNTnXiDPFCPc0GLD1V5RsUq4hBsJThSrfy",
	"5q/2w/TMGYaOqzdArbm2iOvWcQdh9AJ3ITqP2plZw3u1lQ8+ujuGYhNiJyW0jzVVdNSLuVcO58echqpz",
	"GIq0c7ZlObqhUJSM0hPH5J1CFRX5p77I7vrIFEsPyHVU8LFdOCQFo/EUqRlZvLKLy0uO0+K/UFGxDCZv",
	"kEdY8B3HEuo/eoG3HDoTfVy5imAvDM2cIZT1wTxkF3FO4vXiIBhvMhJswE9WWmzR3ngjJalJGSQQHAlO",
	"8PkYLlSaa6IcskiEMyPwWHA/BcqiaJ0wbYkXDgIdzQa0jqpaKvDVM0OTNmpXpRg1QU6Ak7Nllh/oNcP0",
	"6o5rCAc8fkec3oIkexI3NyJFku4Y+jyZI3oogkqHGgN+pJEIjR1xDNIMjCDuyOtxDKOPUuN08KBjeSxI",
	"lcTY/f3d3uY74cZWYT0M/nAaafmLfJfFk+u4l74QXfHPW/Yzi1mgcxjMQABbVZUFA6TUlOdhzwYxRSkq",
	"zy+JsPiUUR5hE3XoKFd2glgZ0/ZdxwjqpNy8yCFPvcs1J9Ppt0ai/lSfxQYlxcjz5rILtRjP4DktVusw",
	"FClwJkf33tgZWaAFbHFPtJcvkxoXrXj4SVBIxrNUtscIVCqZ3EZR/twt8vkJSXmNVWsnBMqaWdvDPCFp",
	"KAU5qU62TXDNFdH6JQ71wdeKQ36zuL1RKRR3JxMATHNwEAjM2ghKcxXbCL7SxiAsKAEpOjrIQNWk2goX",
	"2GBVt7gxrzn0HFXABQop6MrBG35bHbNo7/OiTw/obn1JkFkXPYbbXJ6ysAZ/gFt0HMuP3pfbHiS/8jfF",
	"m/rF08BuRFwcRtV+41/3og580YagRwlrgiFDamEXbyEXXTGR1E2uquD1aECBeZDZK57IyyV4CJG9g8tT",
	"VpfM+pLiLwHFa4G6uWgCfO78gmPaMBVAAB7RTV37AEHy128Vy2niETXsOChCUCaKtu9N0UGcVQChVcdd",
	"FkInekEw1ExPMe26FRjAUHRPQVIQ4+s3UZf7FlcR9ZCDAiSVktsEwi2SQ83XG+LsQr3BTbGLhH1Gb+yn",
	"CiGEZAZEYk4nRdXQgBRkivtQffn94US1Fe4KC5SBs6/9mIRRRlYwXWf0hjA1PCJuZFqkB2xt3Y9Ia0vc",
	"CM7SL3qUYlLG5vv4zcmq/hUPEpEFFBi/PZDfCJFO+J88kygIPzNtYjAyhVcVzS7SdYr7cTO5FHGjN7lS",
	"nrjQSxI41sM7jICG3jTzQMKYuOGJoJ4nJ2sVaZ/tZWFoVOxm8RSCXZnVhIhRj3ryn9DVgvTtzcCvra9C",
	"6mS8LaaiE3eLYlVm/lglrz5vHhdTjHm4jFaGI4V9LIXnyvFi28lglHqv0vkSqzwtgwNLLLDEtVawYJn1",
	"QpfsBfTei8W2ZBY1OCEWBXOzr+1KFgjJn9YZJ3+A7WPxKR68tybtFauRy5wZbh5wc++iWypz78ISRrmX",
	"SYnFddap5+zL8Fhz/l18uD33OjkCnv8i0nDudazS3DiAdQKyL5P7sdeZVbtzr8clsnOuLb6eEX2gvGAD",
	"YCg/wZd8/URpAbdpep7p2C/m7o5jSgLeiJMXBLqjKPc+dc1p9hvqkk3Wd6bF+MJkaedY3TdXTH8tjyn8",
	"gCnz/NEPhgqoAxTtc+3/DwAA//8OTB9oHSIBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
