// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9XXMTR/b3V5nS81RtUiUik4T/k6UqF2BC1rs4cdmwe5GHco2lljx4NKPMi8HrUpUl",
	"BWIwLCwJEEIqGzaBEAgGluwuCQQ+zFiyucpX+Nd098z0zHT3tEYaWRa+CLE9M93n5denT58+fXo5V9Sr",
	"NV0DmmXm9i/nDGDWdM0E8JeDcmkafGwD03J/K+qaBTT4o1yrqUpRthRdK5wwdc39m1mcB1XZ/en/GqCc",
	"25/7P4Wg6QJ6ahbeMwzdyNXr9XyuBMyiodTcRnL7c3+WVaUEW5SA+05eAlbxjVw9nzuoytrCjF0sAtPs",
	"Gx1eexRK8CPJE4VLw7iulVWlOAA5TANTt40ikGTVAHJpSQKnFNMyXSImNAsYmqzOAGMRGNmTMrNkWqAa",
	"VccHunVYt7XSAEVR0oEpabqFZBGQckyTbWteN5S/ggGQc8C25oFm4VbDYqnncesQoaiJ/cu5mqHXgGEp",
	"aDipYBGo7g/WUg3k9udMy1C0istIFZimXAGUZ/V8zgAf24rhcvgRbiL44Hg9n5sGH0/ppnWgaCmLirU0",
	"Pg+KC4oW776mykXYRVU+dQRoFWs+t/+tsXyuqmj+r/lI//ncqT26XFP2FPUSqABtDzhlGfIeS67AJk/I",
	"uf259jc/dc6utC9dyOVzi2gUuy14ZOerivbuW/mqfOrdt8aQXEmOEFUsPnTbijNSxE9mZfiwrBtV96ec",
	"2/EeS6mCXBo2nFbDaX7vtFpO84HT/KfTvO20VjvXm+3Vp2HG9KpigWrNWoLa2SFSPWiXKoAmS1VGVjUF",
	"hatnXt78OiIbDejld8vAtJRFWZXKyilQkmqGfgIULUm3LVMpAcnQ9SqUnSZXQcq+L11on2WIJi4N2E8e",
	"80oI5b1FoKF/KIKRVaCVZGN2UQEnCSLndF0FsiYGqeY9p/Wj03rstFac1rOtm3c2v/uFSXTE3iyTENqb",
	"BkJbd3/sfPE3Dn72hrTQa3dO8zundR1yu8rH7V6mikgJ5CM6IBT3vqHbtbjOIvJLw8JDp3XPaT1zWtec",
	"xnqyAOEA3Ds2NgYleUJXNHlOBSnh0r7YbJ/7pn3xwVbrV6d1xWn94DQf9jhQSI4SlAJ5eXPfPkHl+MxG",
	"9XKgVKVNP0VVVqr9UMu9jadfbDz5m9O47jTXYKscxnyW8rvo2BZ05LHioyiB/0yUjpmA4inZJjAmSil5",
	"at12GWr+x2k9mzjEYMm2Fco8gbslSD2iVxRtXFbVObm4QMG0Xkop+a27F7buPHOaj6Hwz4rOZLBDgr5J",
	"WVHjZMmlkgFMvIhznRUz5CeBqvtVPu6G4j/IhiEvCXHxcqWx8eJm+/Sq6zC1zrqTXfNnhreULymLII/6",
	"dtma00tL6WTX+erHztVPOfOoCbTSUd23QyVQlm3Vyu0vy6oJ8mkG3+b6zc1LZ7ZWTm9+fofk1Wncc5pN",
	"JAbUtT3n+jpph+MLOImuOq17HPYQTBnKhcjur245Ayqs3ThePXFgdYeQa1nAqOqmNW4A2QI21RBoSnGh",
	"B/PWWsP+fOsCHGffJFq4/3kbefWyaZ7UjdQm6O8uNloPeIMbdvoO2akrgl6YDdQksmx48026AcTm3Jc8",
	"IQxCfTNKRbNrQ2wZZyzdkCtgcqmsoCk3TJ/31zRyvuI0b8Jxeo/jdewde/udff/vf/Dcr5hT9pyqFNPO",
	"/ad/fHl1LdSbZqtqj5M/wYiIB0Wf9qEgCQYJFbhz+yR435BL4FgNtRtVgwFkM607tvn54617a5uXzmx+",
	"/kgUJbg/gsi/6MbCUbmSwWKC5x/27Le9cJoPmUoT8tEiMnD/o3gSML4Wnmp6n1o2fv1qa+V0mHboHWC3",
	"LD8A4bu47TdfbNMQ5i694jd+/ar9WYOn+HzO+6CfjEG8sVkSWRF4UPJEjwn1YGj7gb9pUNSNEvoXLQIi",
	"mMTvzSI2lnNAs6twCsCRz7wfIcwdTxfI+Cf0Gc44zW+d1mf4B+ybXUMyVpAG+xR77Nz4qXP1IQ42xsQZ",
	"Zhh3TsjN9XPH52WtAmYsuwQ06wO7OkfzpszoYyJm+U6+5wBQ+/7tzUcXNq/cbV/8L2c2eYdwYrdriZeP",
	"yCIiTWLOIn6kgdG0ZMs201rxn11suZy8iK2bfD5QSFWu1Qx9EZQkA7gONc3GY1IirEwDoFnGEv4fjQVN",
	"t9JGYZvXt1ZaYbrJiMswCwcFxNG/EyVGzCozBhDdiFwJky/VZKV7ymfg4wOoiTgHc7pdmbdSup1bj5+1",
	"T9/qPFl1Gi+2fdI0QFVGLkpqoKLYgGWpoIpj/rgpRbNABRhitvrRL5vr1yh6Chr2ic178vdEx9fiQV9Z",
	"8cXKrti7EbuItKfc4UZZkfSB39iqA7aZQA7QSm5H8SHsb92lENvGL6uu2IbTD676MaBjhppO5EEYqXPu",
	"yuadF8emj2S7tZjP1WyjppspW9+8sb755Sec1rPAH/bHMZACDqIa4AygYKt0ojQNTGAswiyIidIkoAV/",
	"qt5IJzzMN/fty+c0W1XRJohl2CCdd/7Yad1E24ysYCTphNgIWv0nxIVaYv91X4JT8pIrFPw/miMGVy2g",
	"lHazmchfQEOgV78uHmPDBOK2A3QgCzau2nPTul6lZL7oxYXUbN1HPG2e+0/n9BpafekLQOsputhahY7Z",
	"A9H4CWTA6zjgG0W44vwqRV1LbdLg8vM7CPPHMYwxN+VgApKuq3C9knKyaN+/3f75p8QOf4+6m9cNa0Kz",
	"DL1kF9MHajb/cd9pfLL16d32fx9t/vTzxtM1YYYHFS/n7H0SAXNP52FF0OQUxc8hxSzqRmlYg+kemVFd",
	"RyDfMxKYGECh7giJCk+i2MjGqbQMWTPLwPggNWw65x9sPXcBs/n8h3SYCdEQo9xQFqmRcrynmzZseLFz",
	"dkV4YJUVw7Q+yMSD4vX2J1mTe+nxNZhvde514Z4Vc1JOnY/RWfm+vXqLuiejyr2K7/41YSa8znqT3v1r",
	"XUuvJhtAsw70gsvN/57rrNx6ufLt5r9vtk+vdglTRMA4UNXavK6BIKzZMyGdS7+0nzx4eePp1g+PuPFM",
	"2LGGOg5IOtzb+IkQ4zTWaSOK8DYZkvmDXgX9lkz7xi/t9S/ZkgmooovmiNx/yUQHC1cyvcqja1BEPUlP",
	"AJGRS1rdqE30LVWY/rw/KbDGQnSQRmcbHBXeUfMk3rA9Kldoa6hXZdfW9jdt3f+o22S7W7e7W7cD2Lo1",
	"3wf+1u2UKhcB/GfcNgyqB+6umMI88g7jJDT/IcwugzmkUdnQVmpCJBNtsiI0E9oB0ZMn9Tw7GCC2iObs",
	"lXLXwMydT2LNGu+eXMeS3PIE9wfFtHTaLNIfXePm+6rreJt0XU9o47qNYBw+DNY5/2l7/cvOV/94efWz",
	"9pnTTmN9687d9pWL7Rtfd648dFaa7QtfdK7d2nzwSfvGv5zG907jAXoB5o3i5Th8s7H13aedKw8jL7cv",
	"nd94stK5dstprL/89MLWd5/iz5uX97ZvfO007jiNa07jtttEY9VprjkrzQB8XtBnx6PPk39clyg/xKTE",
	"GpWqQtstqedzerlsAsYzI2gvBVoxNQhP6Jc4SvM5S7dkldZ/bMMIEeN94ZOex+wx5RGioD/2C3/0oW1x",
	"vuKH010caoqlyOp4Kgsa+rZHQvwDe7EnBpFylM0o8HvIUwcEIi1seKmSi6vftWHHYJPDNTBidG3jEOHT",
	"sjtY+jVY2KBPA/BIPlZcT5XgYdcojTSOAEH2luRqhDpnUx1vOA43eAyidMCiihv2c0gpl+mDtBLNUqPo",
	"i55pzUnTck0bbJJFVF9sYph0umEMuPcZ8cnOE5IjCY4ogxnqMOADJR12cKueIUFdJGEm6JFOY7i1LoFC",
	"3/WF8Te4JzLDVrZB5gh2g5JYXul24Cigno6hMJEEfMKCSYYT6yg9Sq/oFkaoNaRy3HISfryOoiR5+USU",
	"WBBOkGTIHz82uqHY6wxRfsBroZ5n5yv5zxi6ZtQiqOcTIB+PB6Vj4rCiAppLkpCmxIwKuYPO0Gu62Ytk",
	"p7wWeJlHnLyhpNy79Pafiko46kL1FsiR5vFC5CKF8vcEEpN8rAbBKHLAEkjnjV4GesUTObJcF3ud8ok+",
	"zDzXxiBKjCDcAH6dT8IUge4hllvIuIqnV6Y3V301ByT16OcaYRIGPrangjHMGuahIe0PdPZg5HA4rMBi",
	"FI0Bi14dtS6mItgW4hs1mzT/414i1ODkTHYlmz/TC9kkbdnU86jD7qyKSzHMEqUXvAieW9SER+K5omup",
	"JIrl4TnTfmNi4iXnMXpRGijOEJshniIM0JUVJ46ivZpcVKwl+vBO0lxZ0RRz/pDMWBOUDQDGuR0MQr2H",
	"+UQaZLpx0hszlmxYzKZMztPYcoLslYGFoL2QqAVRcZjyRZiHfKD+iLLoeJqOiqqfWOJZgV2cCeMsn2pb",
	"jKnlLrbFAsMmBG42hpNg3yu487EdPBH2eccQ+CvK8NYemRjsNNY3rz99ef5fnWu3OtebLqFCQVgmnG2e",
	"71LsdgeO57vA1gInDcsCUUDyHxEy6YiMhiuRyfQeSI1Ri67i/rnbUQ7b8mLFbrPJ4WfYS4QaXFury+wo",
	"GEb2P4zvK5g4qI3ZjauBU+AMP2UZafZwMYHh78DHZ400lpSUUBfG0xMNAzYBoaHaZ5jpiPTi9o1BVPys",
	"Nk9Q2dmPCKEkQunA3zEYStJyV3oNxATrxlESYqjWP6qF0EqTeZQBh627hT9uDwdwcONJ4Pf7itEVbqeL",
	"I20CWxXMjYik3QZ+9moXAyIgJM+qHBHpLXQ0jpAT59jfaIqBelYQCgTWiZoE7mf+sIw6bmKjtRjJDUJF",
	"yfoy7IJtsoSKECw3I1S2IWix6zOS1JOIZKuwzNlhP+zbzV4hOGUBzWTHDpihZE45s3o+tzCj/BV05+El",
	"7A92G/BjxbR98GLrjiglBUHwxtoJzMegklhprlsjHWqStzlFYdRkkcbbNhgRnGwLHgJxH9V1SjXWEjre",
	"eUzECBHvBs2ya+R2iyu3pR7yaFnHnWGBKnAkkl8W2ilRqt0ktrsLSSwJdkyftxWgmO8bcslmh4UUE81A",
	"9Kf8o9TCmbMCeRGZ5dZGZmfW6eSwmOk5uaR6w6Il5OhrOQoXfLq5L7OyQEXJHrLBYq33LR1MoOWdnw+W",
	"kNfVWw6XL0G84okpHf89HMqDkJQ2nqxs3f7eaV6Wxo8cmJiclZzWNXgvwxVY4A9d+PHzxtMvnMYFp/H9",
	"1ovPncZ1Z6W58Xxtv6RoZUOW9vx/e2zsLYAbgH/LS3IROqCRh/iv7tgQNHZxwYWXWr0fvxc4PB90xFzM",
	"zcNDE0rKcRVaMHpHRpJkEXTJoDLcXHfrz+T1EdfbWAKyIbBIga9xlkdstHdfC4B/dj/5rD3vTDz3XHvi",
	"OfTk8+LiB7pFzlmLH4IWOJqcdG54oGd8jwSNR6WQdAw4Kgv68eAAgP3IR02dVNrFVEOmfnY1o/BCrcPv",
	"XmbnPIZcxMB1ZLp+rBo3npwDL767hcO2LgJURVs4Zqjh2Y4DfcHjGXQ+cGfhqxwMhdZCaGCIdBqd/Eu5",
	"oD/eOIkuyXZXRexVkQ8W5iihjYgB+HTM+vaxs+bJjhxuC1lNt9Ek9y1yTDz2vfj+luWVe+ALAb0W27Xq",
	"oWYELxqVhihaOQePRHoN/pO6sZBGU+5/SNSw3SRdoW7iBBFNCNWYSEMcTsOGrVGDQYlpbobpRzajh9qy",
	"TZD2idXRTTcJeOmXrKijLw+VKAJJ/B5jMzsQJ1n7gTKYOVoc1sxdnkAHaY66Ld0iDhXUau9DqvttCxoF",
	"rEM1WQwSst9MB0hiQRSOLoZ9YMSUN7gzJiw9bs+4DLauhnN0coI8Kuj6pNrOGnbkcNu+m3z7We6q7iVH",
	"zqIVIv9Cv27v45041HPtsvDlvnVqWuWskphXie/ypbhNWJVp7vZNSF3kJ5VlkzjGvA41aPV4hGmc//dH",
	"nZY6JnxFfPhqeFPswtVeWk+4I/XESYEInvsS0ST9WtOyrKi2AXgBGV5kHHi38vNJCeKt6ANqJMQuFoFp",
	"ioIj9Ho+4CPEsch1mN3N+eTsJnJnY1eamkE8UTKkggdJKVL4zePogpCibSjW0ow7xaCWDgLZAIY7ScJz",
	"mvC3w55Z/ONfjqKwDajCPuDTwE7OW1YNGSlFK+uQGMVyLUDukFJRirrhDsVFYKCsltxbb+x9YwxWwqkB",
	"Ta4p8E9jb7wFQ+TWPCSn4N3DVfAuGnN5103KEQKv4owUXEnmisg/W5Jz1eG9NO6/4woHmNZBfDNuUdcs",
	"PKPJtZqqFOH3hRN43xZNxslT9ce0zuqxuStGtITJyZFac5fUKOO+pmv4huE3x8ZYVPjvFQ6qsrbggaae",
	"z70t9JFcmsZEwE/eSv7kmIa8BOWvANYX2ifSz4RmucNFnQHGIh6/Hh5z+z8KI/Gj4/XjnrsU3M2GQByB",
	"iG5bohhxX00ECXppUChxe0uEiW5bo4GTt8feTv7oA906rNvaMACrsIyWdXUOwkpVRZPKulEEkpwKbX4A",
	"vCYbchVYMOPso+Wca/ugYfT8nf3BIjOMgTwBwOjEcnwXyyOL5RzMkckJQRpWBSssw//VC8WgciyuyxDW",
	"2fvAkvA7EkxQlBRN8gqLhSHNrUwrAmqv2S4xHcdJn4DNr7VLATgGn1SJCm2nzadhjMwH+T5MjMBXpUXF",
	"VCwJv/+GBE+uHrAkp7HmNM9KQCvBX57DoqvhEq7Ny34iWF9quUaOlZIFXtFX7RtfC9V4FcC4lw+VDcbz",
	"UXG/vHFm687qy6tr7e/X0EFZZ6WJZLvx9NbGkzUoh6bTXGu/OL11u+E0zqNfEUOQqI9tAAnGVGFFcekS",
	"2/umE7v57+bGL2d8Yj1cQHLPdU8uZLZ3YrfDevipeHzrgYbTfJC3N+IOPKpaWVj2qlfWkZVRAUrICwvq",
	"EPx74GShj2JjFb3GuOdaZKwSpTR7npK6dV1Gy6fO52o2ZeJA+cpRRUrucDXjHjPzzvJsdZmNy8xkhuc3",
	"Y/mgvKFd53nwBsrk+kARHJvuYlCS4V3XHD9i2i+tTENxZObzqy4HSCuBsmyrVm7/GLxTXqnaVfhzPEpK",
	"b1LFOVWUFve5TcqnUJN7x8gO9lI6GNx86sksYRaNKmSIZsVuVmzuEsIPQAgh0X03zj0HhPGC5hlFIRgg",
	"9Nzirj/cHRAM/SUMDYiQ4RsW3PHgWtJCcV7WKmAPzi3do/l5rVQPI7oMvH9789EFdJ2Y07zcufFT5+pD",
	"d9XZXKP6G26P47DDmUgua4Z+AatTikYRA+0Hz7ce3Qyzegc/en6e5Hl3c0HACsMJm4QcPEu3x/ZPDlLN",
	"bufsi627F9rPTzuNm+hm361vv+rc/3bz88db99bwobjGevvi1fbza789W91cv7l56czWyunNz+/89uws",
	"1ThHi/Fnb06iPSYtU9Et+hKUUMQvHfbZNqRVlroLy6GDlXWmoYmr3GmsI0wU2hd+2niyJqBzb/QTGng/",
	"cq4zeVKOngQdluUOlzGabSOF57TuwnOjd5zmz+gm+t01z8AGhKKh0xdM8M8AS/JekqrwAIYpKeYs+vHd",
	"sqyaQFI0ac5WFyRZK0lFFciGVAOGqWuyKpUVoJbgzoLrlszW0EnM2Zqhl1FaNH2YTHh0bVvIZbtmJCM4",
	"HZg8GZ250D5962XrTq8zkXckcTCzkH+9h9gMhCWyUyYfT4EUpRaW/QOWnOkmrNQe5hos52niUKdINC14",
	"e5jmlxgzr9S8sn3QRef59lS8w4pUzKKXZuFLTvPyxpOVztqPQkuwmdBxwVfG1gd3JTADPegVSVVMi2a3",
	"D3rXAaQLLYpGTLwLBNDpzW3crfeu9GHPGaTARiVmjXECt1moqUkoyVXyL4eIpyL5QMkwRYitnFDvica3",
	"73jxb3Li4Aavbef8O6NGZEPWx05gcArL3gUkdQHbwzY7B4NrTJI9CuLOk2FK/xEHSCWQyMjZFSo20NTP",
	"nO2PkQNGmlvy6zcZOn1JFxb1AbxtliVysnJFaZzsWr3tdra8SmHdQByVt5nF15wJ5KSgT19D30n4u9cZ",
	"qSlhPaCKtfhytIHbzO4c6AE6NIm2JVHYsRE5SEkPxsaEOdq1NTvHw/JMzJxuV+YtsdnUQzz6RhjwB1EX",
	"o4N3zNAu3Hce3GsyOnctDnb3C2GoT8lKaYSADtnZhfkOhDnanejaccTfdeM4TuGudh3Hbh1HprBZo3Eg",
	"kh6ofcEc7ZqYoTUxYDHplB58g7kTgKq19G0jIPvIG76clx9wI3gelaAbUjQ7lj+lm5hvaiDf03OGcXyi",
	"+g9FPXivARB0DMxsdEndqEHGtxOFZXztYj3ZYjCNxXv+zY3J0xx51+nwBO9DbIhYklE0Ihw3iGFF7AHq",
	"f5uMVEQAQ2akIo4NAc1X80wWx74VjMht7rz9b+QtkF8wZ9D45cfDOA7Y941zjqWI1J9rr3/Z/uxmLp9b",
	"lFUFpb37HOWrivbuXlo1vqqiHQFaxVXg3jQl9Dpff+M01nGFvqS+w3egC5z3FqSAPKpOJyJU268PPLcv",
	"XeBxm6/Kp959c98+XNCLcb96nwSw8cvq5k+fCMqAdUF7X2kh6xxwaDEzIKDz9TdCvUcKrVFLEopc4k5e",
	"1s66290f5PGajnxvN2L3+jvlsQ1ReuPTl3KfIZNSD9+InknNz4GYpd6Ki2KTs03mJNJtv1TR+fobrIHB",
	"W6VB2Z86+3L9sETzQ2SDPGe2yLJFI3aKhuesLofUJFLjJNllRS8ynNYMl295xsGAcN+9hAPephw0wmAq",
	"saQzomDKJ4V9eQiJREJGBR5ZRovCMhIKQo8ICtOGkfjLantUELi7Tt9dp++u03fX6b36yIPeTU81udks",
	"+/7quuyFqkgWeHWpd8d9Euz6Zr3Bt8RRxivioeEAoBAeeU7aTgNjVslTPAFRkDi5NIDYa0ajp8iBzihu",
	"LFa8i5CYK234BjPBCl2klPVJaxOA0nZnZiFOExbFhLBGBS0IIYmnrDVwEnFP3V32YJJh6gOhn4EnNiRi",
	"A5sVJKDRydX0sOFbEuJ0rBBYpJOKNS/J2pJUVGWl+oYE/dTOnR9eXr/kNC93zjecxnfhEn/nN54+7Xxy",
	"0Wmsw0+cxrrTfOi07sEK+dec5uWNX7/qrF5qX3yw1fqVDUbvpG3WiCTOwQ4tLKHSRgGc9PpeUYwu43v0",
	"6gLznlL6nSmxKnJ5s8L7/r18InXqvHeHaaURYkNojgsJZtTmOgpWCid0nmH7o65okqUnTYHk7Ys7FC1U",
	"XjiQORGSzCucz8cDl38TI+OOrRKqXCwMMHgBZ6YAy3bWJNnYxrkzRgYd4nJMP7swhzBX9QoymsxZFr4h",
	"HZs+Qptc4aWv2RdeRN1Q9HvEJ65eJ2qVuUwT/BWK5GWn1AH8Z2Ao5SUJfkkbuuHbbTMdXuGuaNdu2Na8",
	"64bDTYptiNwIEemNPBPeNtsLqilarXoXA1N1OQO0EirpCuCLNH1OogcZqhH2QBHMey5N3d6R0k/VsQjz",
	"NeaKD0lu5JYakCsPQ95VywW0yJrlT/FeyNr/zCscxcBX+CJnPN1nijfK1dG02C+NgW0AoRi1Higt3Q/8",
	"xukfnXBNwBxGaU1eqiYdsMXvMCPAU7gNoRjwEpCN7Q7kegQnlVgm+d7JW7/UCmCe5kM4KCzjH5JiI9DZ",
	"rfmKZ2FiymtN7I5I4u1hio3EmOEF1OZBcSEsnhEsHxeAh7UBGxcDZd910CjJantUBCBUiQx6R3QXyQlm",
	"0J5TlWIB3d9QQK8n3nznXf0g0d01V+yw2Un41rjvEmWr6ViXFFW7LIRo78MyCokQyxOvzngiRK+wAgAz",
	"qIHMxYX7oQ2HgD7GahFx0IcgAOpqMFGASF9DGgZIpjIeB0hloX6f/Mm4rpVVpWj1OdaAijExhwj6WMIl",
	"m6BNpo4T1Er24wT1Q4OLqkozS6YFqqb0oUeerPZDWlhEpLwKRdWemzV0vcq/wV+15yT3LSxAtujGVXtu",
	"2m1uQCL0+0u6Tj/CgVSTKztguy2mOv5RikQ9Tdk0PWXlzyWriEKwkHEMt/Lhn3aCS8UYhrohV0ChugT3",
	"f3mD0H2BGTyYQe1MLuH99cwHH9kdRbEBsaOyHYM1lVRai37jmDsHxzSUnVOSpJ1jNVWXSxJBySBXT5i8",
	"w4rKuLoPx3C9jIiBKZYckMtlSF49cUhyRiPmUGQ1XvZeHaaATaKifBmM3iB3sWDpusrVv/sCa8l11P04",
	"cxXBXiiaOepR1gXzkF3EubfHwg9csiYjTtLEaKUyJ+UzVEKSGpVBAsER4ASfaWJCpbrEy/tzRTg5AI8F",
	"95OgLILWEdMWf+HA0dGUTeooq6UCWz2TJGmDdlWSUWPHBDg625zxgV4oKWZRN0rcAY/f4ackIckews0N",
	"SJFedxR9HooR3RdBhcOZNjua6QmNHtW0wwwMILbJ6nEII5xC47T3BKf0WAjdjM0aOVuf3m2vnnEa64m3",
	"/7OH00Av+493mTy5DvtF/7wLzVnLfurV/ejsDDUQQFdVZsEAITXFedi2QUxQ+iGseCCIMP9kWBxhI3VQ",
	"LHbJPmllbNkCJe49+3gQwhc5UeJAF6jJXU9rGyYNzTKTVlbyoqyo8pwKga9ZplQ29Co6A2iiM4HjRw5M",
	"TM5KNQOUlVPcqcPtbnCD3O1NaMLQhneGoKhN0SxDL9lFr1gST3mhd5mamQi/NRD9hPpM1lKIkVdt4czV",
	"om9KY1rM1m1PUuBkjO7tme1FgWbTxT3SM4BIUrE7G7LTR5GMp4g8uQGoVDAtmKD8lQu1sVM54xrL1k5w",
	"lDW5tI0ZlsJQsmNSHW2bYCiLvCiCH3CHryUH3qdwe4NSKO5OJAwf5mA3HB+1EYTmMrYRbKUNQXBeAFLk",
	"ypGCqlG1FQYAmmUsMcMB7TMX2qdvvWzdQRGf356tds4/2Hr+rP3No/bfzzmNO+1L5zvXm789O8tG4TTu",
	"I3sUej3RoldhRrYNiphEFLbi0BsJWWE9jWC0ykNgFJcaOCmrTFxOo+feqQBVqSoWD4GotSGLUL0qdgZz",
	"WFAVbcEM1zal1St1hTiFPjkCvxBKE1H4mVH86z+YiSDcsp8uc7OYuVnE3E53QUy7WpXd+SAXKgTWuua0",
	"7jutK07zW/jrPad112k9dpoPnObl9tlzL69/5zSuO03XrpIoiEiH3CChb3pE9N6fauhu58cMNd1VNmhv",
	"mlaS2zZUVJB77O134qWfvU6Pi5dU4c4ALLB1bTEyR07n6kOncc1pfEKCZPP605fn/yUGEt9wmEA2ivOc",
	"AxvuYygZU5pbgj/gitvUpQx6X8yceL+yLUpVPuWXex/Lc6u/D0OemUkIa4TnmmX3X6Ej1UnV5lyBHoON",
	"CWXn2t6rw5SdS/AgkoI4knXmWAgRLcdrSifnleK8ZM0DyayBolJWAC5BdUJXNLjxyQEPr2jvDkCQeCXe",
	"ZDmNPKL6vbGHEBTZFtrxpmh345ADoZO6scCFjvsCZ6gppqRoRdUugZIkmxKSAh9ff3G73LG4cqmHHCQg",
	"KZXcRhBurhwKllzhH1qRK8yTG66wj8qV/h3eGAxGXJIpEPE5HRVVQwOScADRguqLr8AD1WaYbMhRBj7U",
	"Z/kkDDI+i+k6Kle4Jw5d4gamRXLAFpYtlzSRKz1p+kWPQkyK2HwLv9mzyU9YaKqytoDN9SAHCc8Ccozf",
	"NshvgEj3+B89k8jZT6XaRHtgCs9qYyxJ1yHuh83kEsQN3uQKeeJcL4njWPfvjCsaehPUc65D4oYHgnqV",
	"nKyTSPt0LwtDI2M3i6UQ7MqcDIgY9Kj3/uO6WpC+7Rn4heWTkDoRb4uq6MDdIlgVmT9Oeq++ah4XVYxx",
	"uAxWhgOFvS+FV8rxottJe5B6z9L54qs8LINdS8yxxLhiaKJL9hp67/VkW4IKd46KRcHc7Gi7EgVC8Kdl",
	"yoFyoFlYfJIJyyGGveKc6zJHhpsJjNi7qGB97F14m2nsZXSfZ/xtWEwn+jKslhN/F9dMir3uVRaKf+Fq",
	"OPY6VmlsHMArw6Ive1flRN8+aJcqIM7mHPwz5X2cbo8/kF7TAChJv8P1fn8n1YBRVUxT0bXXY2WkqZKA",
	"hRbjgkClL2PvEzceRL8h6u3TvlNUyhcKTTvwEsE4oNDVgvG3i5ayqFhL8Q/wA5oM4UiNfYHtG02j8fPK",
	"FAUTp37jbUyHE0hjn3tpmPXj9f8NAAD//5RgkD5CYAEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
