// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdfXPcRJr/KirdVQFVgnEI7O2lij/yQiBsAq44gT+oVEoetccda6RBatnxuqYq8WzY",
	"AMvB1R7kWKg7cruwvCZwcMvytvkwg+3kW1ypX6RuqbvVoxmN7bH/INiW1P28/Prpp59+up8Nux12e2EA",
	"AhTbxzbsCMS9MIgB/uWE650HryQgRulv7TBAIMA/ur2eD9sugmHQuhKHQfq3uL0Mum760z9HYMk+Zv9T",
	"K2+6RZ7GraejKIzsfr/v2B6I2xHspY3Yx+wXXR96uEULpO84FkDtx+y+Y5/w3WBlIWm3QRxPjA7WnoQS",
	"+shiokhpOBMgEAWuvwCiVRA1L42F9RiBblESz4fodJgEXvP9nwdxmERtYHkhiK0gRBa4CmOUk3IxcBO0",
	"HEbwt2AK5BxP0DIIEG1VFEvfoa1jcJAmjm3YvSjsgQhBgmQfrAI//QGt94B9zI5RBINOykgXxLHbAZJn",
	"fceOwCsJjFIOX6ZN5B9c6jv2efDKfBij420EVyFaP7kM2iswKHff89027qLrXj0Lgg5ato8dnXPsLgyy",
	"X51C/4599dHQ7cFH26EHOiB4FFxFkfsocju4ySuufcze+vDb7deubb39pu3Yq2QApS0wsp0uDJ466nTd",
	"q08dnSNy5TkiVKn4CBNUZqRNn1x28cOlMOqmP9lpx48i2AV2HTaGg+vDzb8OB4Ph5t3h5v8MNz8eDm5u",
	"v7e5dfNHkbGwCxHo9tA61s4+keqJxOsAmSx9lxi0GhTefPXB7f8qyCYA4dJTSyBGcNX1rSV4FXhWLwqv",
	"gDaywgTF0ANWFIZdLLvA7YKafb/95tZrCtGUpYH7cSivnFCeicKkV5aJMOzrUDfc/Go4+Hw4+Gk4uDW8",
	"fuf+Z19s/+e/afR4BOvxyNzcHBYLjI97XRhk1FECFsPQB25gRMHOnds7b796/9oNgZTBO8PBp8PNr3Av",
	"V0IYuIs+qNnD1lubW69/uPXW3fuDn8WG62uVJ1aPfCKxx598UqlsXokcswXpFsGA/znjXYyBxH4nMYjO",
	"eDVZG3yc8rX5t+HgpzOnFJwlCZSgl3bLkXo27MDgpOv7i257RTKmQ6+mAu5/9ub9T34abn6DdfCa6fjC",
	"HXL0nXOhXybL9bwIxNSrS01oLFhv0E2/csqTI/2DG0XuuhEXD65d/+Xe7a0bN1MzPnhtOPhiuPm9woY7",
	"HlwFDuk7ZWsx9NbryW77gy+23/29UmSOHYPAuxBi8BErs+QmPrKPLbl+DJyxRvnOf3zC8zq8/vlwc5OI",
	"gXSdLKYWuO6ovDfc/MtwcHM4+FzDHoGpQrkY2ZPVrWZAidot45WJg6pbQC5CIOqGMToZAReBRGoIAthe",
	"GcPKDd6gXsbgTTzOPqyc4h9/nPgabhyvhVFtE/TvKTYGd3WDG3f6a9zpr57I9DoOs7maTJwZzKnEAFKr",
	"nkmeEwanvgXYCZLeHraMCyiM3A44t74Eycwr0sf+WkfO7ww3b+Nx+rlKyNjHeOLXT/7LrzJHYz5Z9GG7",
	"rgtw44sH774h9BYkvj+mD8AxogFMxeyPBckxyKngpTBaueB2GnD7dH7e2J7RveHmV0p5GHlBBRmk/0km",
	"abygFq34+Fb7l58/uH/thkg7nnipx+NMQfgpJCbNl3rUidzVV/wvP3+w9cfrOsU7NvtgkoxhvKlZMvG5",
	"GZSY6CmhDIZJttI/D9ph5JF/iX9dwCR97zJhY8MGQdLF1pWGOpwsJGBfqrX0T5f7d4eDV4ebfx4O/kh/",
	"oG7PLSJjSDQ4oWDD9vvfbr/7FY0ulMQpMkw7z+VG1vLk3zNe5lCKQouRi5K4rrX5PpVBOm/fK7vOeIkf",
	"Abykd3u9KFwFVs+VwYLSoKJ8AT8+Tpooc7AYJp1lVHNuuv/NT1s3Ptr++83h9Xu7Pvwj0HWJsa0R6dh8",
	"7/61AV1AIOSDLo1w0qZggEAHRGao+/qHnTu3JHrKG86IdZj8mej0WjyRKavs0RyKfRSxm0h7Ph1uJVlP",
	"hN8CjbTNCnJA4KUdlYdwFnWsIbZffriZim1vzujdbKF4MfLriTxfa26//s7OJ/cunj/bbFTUsXtJ1Avj",
	"mq3vvH9n50+/07TeBP6oZ0GBlHNQ1IBmAD29CgLyzxnvPIhBtIo3cM5454BshdgtjPSR5s1vhoPbw8E3",
	"w8FNUU75esWxk7qASQGiaLW07OxSs5J2loti3l1P/07/J/O1sCMFvJqzLr+HQrAcIjBZQDACads5b8QU",
	"nfSTxfNh2JXsvoXtldpsfUl42nn9b9s33iAOYbgCgrFiCYOb2MO6a7qkwwywjnO+L8YgkiEZtsOgtm3C",
	"HvFfMJ6/KcFOGYnHm6Bh6D8TuUKcZRSrv/Xlx1vff1vZ4b+S7pbDCJ0JUBR6Sbv+2nHnv78cXv/d/d9/",
	"tvXd1zvffv/Lj28YMzyt6Jhmw4MLjzGdi4qQyamIn1MwTpdfezV0xsgs6roA+bGRoMQACWwVSIQ6iVIj",
	"W6YSRW4QL4Ho+dqw2f7D3fv/SAGz849P62FGoKFEeQRXXQSUOzh1Ixlvbb92zXhgLcEoRs834grpevuN",
	"G7jj9PjwcPPz4eD1R4x7hvE5t/Ym7Pa1v27d/EgagfXdccX35S1jJlhn40nvy1sjS6/nRiBAx8fB5c53",
	"r29f++jBtT/v/N/trRs3R4QpIeAk8P3echiA55PuItkxGpuQ7bd/2Pr73Qfv/3j/06933vls663vFETh",
	"jgPScU7S6fHGT4GY4fU7shGVb7SpJPNs2AWTlszW+z9s3fmTWjI5VXLRnHUnL5niYNFKZlx5jAyKoifJ",
	"BFAYubzVLdrEzFKJ9DvZpKAaC8VBms82dCfmgtuRrUQOynZMku3GpP9J49+HezKHezJT2JOJnwHZnsy8",
	"77YB/udkEkVSPzZdd4g86tJqK5p/AWdk4Lyromxk6x0jkrk2VXGOM8Fx0xzSvqNeUpstRbMkGeUjOSYV",
	"CWEOv/Ird8+vBnludYJ7FsYojNab0jVtfqK6Lrcp1/WZ4GSYSEP4+16xjLWymFJ5XMSNkt3VWBIWg12o",
	"kEq4tBQDxbMob68GJEp0EfWRX8qgcGwUIteXUVLariBksS8yJhzKqIGMBFomYzjoRy8kSPNVunIjCbko",
	"SoDM/AQQQdc/Wct0Cd+OSUiW8156EnGb+HqsZ2+y5kQrJeU2V54qnZ3sE4wKS9Ia0TttucowsY6KJLGN",
	"MYkXR/a5veNIKjn6OBqFYtYZofw4a6HvqDfesmcKY6U4D5A+wQmRKvLLnlw9Jk5DH8gMQMV+m9KfS9Ea",
	"hb0wHkey86wF3RaaZgOsahM5fa5I10jnj56nFLwUlXhQCWcesvY5aXCbasJGtMEOW4bV3I3M0eHwSOep",
	"Vw2VAnrNNzKanHZZp3qiTyuzOBVEmRFEG6Cv60mY59C9h+UmGFfzPIH65mqi5oCnnvzc40zC1Mf2fD6G",
	"VcNcGNLZQFcPRg2HexVYeEu/TB1YZceIR5iKcFuEb9Js1fxPeylQQ7MMJF6j64PAc6MXIViTxPqrgi19",
	"h3Q4mlVJKcbpDvJTXvlzJN3w557DMKglUSoP5lFnjZmJl5/HxDCGIE6BTYGnAgNyZZWJk2iv57YhWpcP",
	"7yrNLcEAxsunXCTX0VIEwEltB9NQ72k9kRGfN1P1xgJyI6RsKtY8La0R+F4VWMjbE0RtiIrTki9EHpxc",
	"/QVlyfF0viiqSWJJZwUOcWaMM6dWQEup5RECWrlhMwK3GsNVsB8X3E4p9mbCvnk+XXFFKd61wCfGDK/f",
	"2Xnvxwd/+N/tWx9tv7eZEmoU8lDCOdH5Lu1RA3w63wW3ljtpQlYez39ByLwjMhuuRCPTey41xUH+Tvrn",
	"UUc5botogDRbNaRpLwVq6EnyEfc1+w5pTqGdipsB9Kf66VOVkVYPlxhEmth5HUvKS2gE48lEo4BNTqhw",
	"4J8yXZBe2b4piCqf/tUJqjn7USCUR6gc+PsGQ1VaHkmvuZjwLQmSrSyp9S9qQVhpKlP5euTBqPCn7dEA",
	"Dm28CvxZXyW6xHZGSOlWJmjjVBkuR1ziXCUeCJAqiSXlRZvlOMKAyAlx8sEh9l/oTUgN5+SkSXufTTFI",
	"c+VTgZBz8hMZGwtZcKvi/KHKFxAOCeYtjpzIL02X51vFJ+9PZ7HZwiDR7m6AqwgEsXqBr4z3ak7Y9x17",
	"ZQH+FozmhukChhWerTdC4DlDGDXBhFJeEBxvYvQ/p9ApQaXy8oNRLanQpG4HScJorCJNF9ufEZzsCh5y",
	"cV8IQ8kFQR45g3DRxAhx7+bNqq9tGhVXaUtjpKmozuTgg93gbCHlItcL40odRNfF3qkfJMeQ/mSOcZ5L",
	"9YzXXCZMYbJTHXYRhSjPoOEVkQuuqEB6KGYi8+T451cMTp/kHSm9wWWcLwVBnRGRNUuGBssWqxodeZcK",
	"KsXmRnNgqx0srSVcB25ksCbBr2n8K5mRq3uYRn/4pfqwiu5QifZgSOVBjuoDF+YnIkwOKpifIjDI7a9K",
	"vJ9qkvzZvPGiFKry6IuykOfXSyaxkfZxfRisXE4iXzQTUl/I/BpWrl3xdrgIyt6lg2qE9osqZJ05PK1C",
	"w5ckuUa7nPHJzWuSmSvjSdRz7jJM0+M4dCpUToVMO1OY/JWXm5XOI1TP+LQtYkHSRqvm+cJRgtL35pFU",
	"xI4E6YVAXivFR8c4V6RbUtUhSnbkh5Eov4BtLYxW6mgq/Y+IGrdbpSvSTZkgrgmjc0h1iKMJf7g1Wa6n",
	"TgOT6l2KZweLxUTJ9L1My/m5Gskg0HC/V3OrdGKb5jAe9VicOSBIq1VQrM7tGT1mJaNAlfbcxFDg+53w",
	"MBjxsJlGF3t9YJSUN70sYJUed2dc5nHLvTk6NatoH4x8lmB/DTt+uNWtd1CRkaDfK25mP1h5tX/eapFp",
	"uq3/XCjbETauviJWXYnNqgaM03rFRf9X1gzyxtOXuCbld/MvudBPIqBb7eviVYAVvNGTkkdByAfSxTcp",
	"fGQKDuF1J+dD4NjkTvfRJgreJJpcPD6SprgyU4U91fxB1aYqffMSucCynUQQrS+kdokW1QJuBKLUsuLj",
	"F/i30yzA8txLF2xazwj3gZ/mwZZlhHrkuDkMlkJMDESpBbBPwQ5sh1E6FFdBRPbB7KOPHXlsDh8n7YHA",
	"7UH8p7nHjuLAFVrG5LTYjbetNle9KIwlmYHs2KaVX/6biihLGbVltZCIcECMTtDyDhOpFKUovCQrHVUg",
	"2qLk2LzWUJQAkkiXFz97fG5ORUX2XkuoTdZ37CeMPsrLquFPjlZ/IpTb6jv2kyb9FIqW8Xi0j70sIvHl",
	"S/1LbI7Nb0EmIC5AhBWGMsBI+molSMhL00JJ2lslTMIEzQZOnph7ovqjrKzc7gOrtUHWAn0NwrwuDKyl",
	"MGoDy62FtiyS2HMjtwsQ3qN+ecNObR82jMzfOZavTEQMOBwAixPLpUMsH2ws4zP1rQ38v36rnd/hQs9Z",
	"isp6BiCLvmPhXAYLBhY7li9iWXtHjAmaWbMjgrkMkAkhWn/rjaY0Z6cotP02kYoYWc6335UYwa9aqzCG",
	"yGLvGwHk2ezlJgDi0HZeSQDugzUEIhjq7SarJOHhO5jWAFixHbsbBmi5XElC2Y/HDtioehG2LiW7lrsB",
	"8Cx5Qw9wovHlPNNjxp1Lci1Ja4NdT0J8gEQyHi7iTeR89idfWAh2caiz4AEoq52YjAjurpQ94QIomdH5",
	"AVQ+ZO/90BmYJqjT2Slzalvc1U1KQ5++W4R2rDP15ZumGvJsVbaeThojf5jdD5V/mVVmJGV8YTedI+Yc",
	"SShK3qRP0wolLT6ZNuleJU0emeM7OCLpYHoTQ1l/FRMDRggDxv4w8vktI0rck1csH8ZIhvYTWRkKCbSr",
	"gWUKIHb1Bsk02UW/mF2GpYYCL7BZMaMUJ5f6jmL1T+LIVnatSnm1nwGlwVW4WjlC75Vz68Txkt2BpsEN",
	"dQMWs9vWZsSvzLCTG5zWBru6p29ge9Rm50R+AVD1zMrdFrSXFtrmAOnkEpk5uyLFRsvNCvlplhvU3i6u",
	"W+R1yUJDVh6wWcg0tcqQcXJo7nbZ3NkuPStjjmxyxPOym1d69IAPECij/BT+O5XTw+Q7VmTykRLYydu6",
	"opLTNpWjrVOn6MdUmpRKYVeU75wFCyNydGhp9o9jxUxMXjPWHPHkG2PAn2BlUWcF75ShQ7jvP7j3WB1Y",
	"Y7CnXxhDHZeZnR2gz2dFqg9hvr9gntcXHslxpN+N4jiyUsaHjuOojqNS2BVFo2fIvlCODk3MnjUxYLUq",
	"DQa/odwAIHcyTiz+33zAjd5mrY+zcTzPSqyNKJpTemuDXjrZr1a/UvNPZ/dWVtss/qbXvROAFdgwgcVB",
	"QERrQ7iM1wAhFvdBFVrOFy76bQY6jiJzROx7r0JRlJGRuYrE6+QPGkZbXZNAanfdAK/kXaU6zoFD0I4H",
	"Wk+jjFmDrmLJQLfMjfA4n6CZAWNT6w+dgCRIPCeX+7RXI7VGT1sDnVk0/B12SlfpguA3lGsUdr91szlK",
	"MQDebi9u6P3sem+BE9asoKWT3XStzU8KwBrhXpqixGDSYIYSp5+pWppC31qz0mF3/M9IuINhI7MkrQ16",
	"gL5vYFOg91Bs9aIQ39Crsi3PZAfyqyfi/PD+XvLiBDaM7IcgmFmzIxKstK6EulPYz4UwsFBYZV74axf2",
	"KVqkvGggc0WQzAE+jKADV3YFg+JwrUfSy40BdjFmF2E2BbBm50iejV2cLktkyCHulvRzCHMMc59VHFHO",
	"svgN6+L5s7LJlRQsaXzyI91I9Hs2I67f5w5RpExz/LXa/C0n0gH8Iojg0rqFv5QNXfFam0aHl9iV7Hxa",
	"gpYtGJAjmruwKjYiko28mNTtGAPVEq122Y1AUl0ugMCzFhN/xQL4RZk+z5EHDaoR9yARzNMpTaMeJpyk",
	"6lSEZRpLxUckN3NZv5grhiF2x1KLrKsu66d4Fg7MPrPcdpve4STDl3iDE53uG8Wb5M4oWVxNxsAugNCM",
	"WgZKFGZBtTL9s7MUzpmjKO3lRRHUVxyQd5TRNVZYwSi+RssG7GqQLKsvVnHQn+d7HztnNsOxAAWmeQEH",
	"rY2sqFa/+jR0L1O8ChPzXIkug2suuLf3UmykxIwuhrYM2iuiePb5LKcHj2pzqywGyZ7WtFHS1NaTCUCk",
	"Epn2btMhkvVmMM6qACotH3lFtWClZQQbVyTtR6a+nD7F6oZwMIFFa+GKz0bdz0Jfe3TZWk1lo+vWvMKk",
	"FL7kY4tmJ+PxLcUwaaV5DJN+ZKr0fWthPUagG1svMPJcfxLSympr5vJqtf1k8XJEK2uqb4Pzk0UrfYsK",
	"UC26rFDnlESY9Vd1NVuBA6vndvbB1k1Jdfoc/Eo9zScyPTXlG1SrSEKwkeESW3nhN/thelYMQ1xqtNXN",
	"yqAqB2H6gnIhKlZTncLg47uTKDYndlZC+1RTmkSLdBa0pHvleH4saag5h6FKOxd7fuh6FkfJND1xsfiy",
	"bL1AwlFsd31qiuUH5AYpuNGvHJKa0Xia1eyoXtll5T320uK/UlGZDGZvkKdYQLQwsVL/6Quq5RCuaty4",
	"inAvEs1cYJSNwDxml3DO4vX6IJhqMtJswM9WymHV3nhHkNSsDBIMjhwn9OyBEirddV0OGS2OPRVVybOh",
	"eWVxtM6YtvQLB42O5hNeR00tFdTqOceTNm1XpRo1SUmAs7NlVh7oLS8vgq4c8PQdfXqLWFN9Sopk3Un0",
	"eapE9EQEJYYaE3WkkQlNHnFMRAamEHdU9bgHo49G43T8oGN9LBSL+eqmSihWEVaMm0Kt4alIV+izeh4V",
	"GDlok6lWi9nYKmmx2aFcpcBzJbp3ZxibAi2Ri3um51+TpJXUF1GnJxAZz3P7sFNQqWHaCUf5gXO/1akC",
	"ZY01ayc0yjq3vos7+MZQSkpSnW2bEMFVFxkswvFr1YvxedretBRKuzNZmoscHC7RizaC01zDNkKttD2w",
	"YDeAFL9ul6BqVm1FBAKw5vrK1eh58pxUewEWK16iwBt9295jcZiDos8YuFF7WZPzkj6mJfwW1y2ulL3U",
	"8pP3zQL37Ff1dlXXvXoWBJ2UiyOksk32627UPKsK1cecsGYYMnwxU/3mTtXh77xGUKNlSxsHBeXBZBdn",
	"Jo99qxBievNIbK0tw/ayhZaBFfdAGy5BQE+EXglhgDfpNODR3U+yDxBkfulItZxmHlGTjoMSBBWiaPve",
	"FB3GWTUQWgujFS100hc0Qw3GFgzafuIBz3Jji0hBj6+X0i73La5S6jEHFUiqJbcZhFsqhxZyO/q8H7ej",
	"TH5JhX3B7eyna4EZyRKIZJzOiqqxAanI4URYfeUUzly1DSZvapRB8yJRRsI0IyuUrgtuR5u0mRI3NS3y",
	"A7a1gVLS+gb3oMr0Sx4JTJrYfETfnK0r/7NBorOAGuO3C/KbItIZ/7NnEjXhZ6lNTKam8Kai2VW6Frjf",
	"ayaXI276JtfIE9d6SRrHenJpwmTo7XrtZJ0bngvqIDlZa0T7ci+LQqNhN0ulEOrKrOVETHvUs/+0rham",
	"b3cGfmtjDVNn4m1JFZ27WxyrJvPHGnv1oHlcUjGW4TJdGU4V9pkUDpTjJbeTyTT13qTzpVe5KINDS6yx",
	"xK1esujDdqVL9jB575FqWzJPGpwRi0K52dd2pQiE/E8bkpx8ECAqPivGN0qIXrGdusyF4RaDqPQuuT+u",
	"9C4u3FB6mVWJ2pCdRyy+jA8clt+lx05Lr7PDmeUvUg2XXqcqLY0DfIN38WV2c+2GtFRf6fWsLl7JtaUX",
	"p5EPrIcDADzrIXr9zkNWD0RdGMcwDB4p3eoklQS+q6IsCHJ7SOl97gLC4jfc9Xey76Av+QLKtHO8jeAq",
	"ROtlTNEHdv9S//8DAAD//3lzz2zEBQEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
