openapi: 3.0.3
info:
  version: 3.1.0
  title: Digicore
servers:
  - url: 'http://{host}:{port}/'
    description: develop
    variables:
      host:
        default: localhost
      port:
        default: '8000'
tags:
  - name: auth
    description: Authentication system
  - name: user
    description: User system
paths:
  /status:
    get:
      description: Server status check
      responses:
        '200':
          description: All Systems Operational
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetStatus'
        '500':
          $ref: '#/components/responses/InternalServer'
  /signup:
    get:
      tags:
        - auth
      description: Get signup URL
      responses:
        '200':
          description: Signup URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetSignup'
  /signup/callback:
    post:
      tags:
        - auth
      description: Verify auth
      requestBody:
        description: Auth information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqPostSignupCallback'
      responses:
        '200':
          description: Success signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResPostSignupCallback'
        '500':
          $ref: '#/components/responses/InternalServer'
  /login:
    get:
      tags:
        - auth
      description: Get login URL
      responses:
        '200':
          description: Login URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetLogin'
  /login/callback:
    post:
      tags:
        - auth
      description: Verify auth
      requestBody:
        description: Auth information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqPostLoginCallback'
      responses:
        '200':
          description: Success signup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResPostLoginCallback'
        '500':
          $ref: '#/components/responses/InternalServer'
  /user/me:
    get:
      tags:
        - user
      description: Get my profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success get my profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetUserMe'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
    put:
      tags:
        - user
      description: Update my profile
      security:
        - BearerAuth: []
      requestBody:
        description: My profile
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqPutUserMe'
      responses:
        '200':
          description: Success update my profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetUserMe'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
  /user/me/private:
    get:
      tags:
        - user
      description: Get my private profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success get my private profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetUserMePrivate'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
    put:
      tags:
        - user
      description: Update my profile
      security:
        - BearerAuth: []
      requestBody:
        description: My profile
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqPutUserMePrivate'
      responses:
        '200':
          description: Success update my private profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResGetUserMePrivate'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
  /user/me/payment:
    get:
      tags:
        - user
      description: Get my payment
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success get my payment
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResGetUserMePayment'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServer'
    put:
      tags:
        - user
      description: Update my payment
      security:
        - BearerAuth: []
      requestBody:
        description: My payment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReqPutUserMePayment'
      responses:
        '200':
          description: Success update my payment
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResGetUserMePayment'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServer'
components:
  schemas:
    ResGetStatus:
      required:
        - status
      properties:
        status:
          type: boolean
    ResGetSignup:
      required:
        - url
      properties:
        url:
          type: string
    ReqPostSignupCallback:
      required:
        - code
      properties:
        code:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
            ja: 認証コード
    ResPostSignupCallback:
      required:
        - jwt
      properties:
        jwt:
          type: string
    ResGetLogin:
      required:
        - url
      properties:
        url:
          type: string
    ReqPostLoginCallback:
      required:
        - code
      properties:
        code:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
            ja: 認証コード
    ResPostLoginCallback:
      required:
        - jwt
      properties:
        jwt:
          type: string
    ResGetUserMe:
      required:
        - user_id
        - username
        - student_number
        - icon_url
        - school_grade
        - discord_userid
        - short_self_introduction
        - active_limit
      properties:
        user_id:
          type: string
        username:
          type: string
        student_number:
          type: string
        icon_url:
          type: string
        school_grade:
          type: integer
        discord_userid:
          type: string
        short_self_introduction:
          type: string
        active_limit:
          type: string
    ReqPutUserMe:
      required:
        - username
        - icon_url
        - school_grade
        - short_self_introduction
      properties:
        username:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: ユーザー名
        icon_url:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: アイコンURL
        school_grade:
          type: integer
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=9'
            ja: 学年
        short_self_introduction:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 短い自己紹介
    ResGetUserMePrivate:
      required:
        - last_name
        - last_name_kana
        - first_name
        - first_name_kana
        - is_male
        - phone_number
        - address
        - parent_name
        - parent_cellphone_number
        - parent_homephone_number
        - parent_address
      properties:
        last_name:
          type: string
        last_name_kana:
          type: string
        first_name:
          type: string
        first_name_kana:
          type: string
        is_male:
          type: boolean
        phone_number:
          type: string
        address:
          type: string
        parent_name:
          type: string
        parent_cellphone_number:
          type: string
        parent_homephone_number:
          type: string
        parent_address:
          type: string
    ReqPutUserMePrivate:
      required:
        - last_name
        - last_name_kana
        - first_name
        - first_name_kana
        - is_male
        - phone_number
        - address
        - parent_name
        - parent_cellphone_number
        - parent_homephone_number
        - parent_address
      properties:
        last_name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 名字
        last_name_kana:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 名字(カナ)
        first_name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 名前
        first_name_kana:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 名前(カナ)
        is_male:
          type: boolean
          x-oapi-codegen-extra-tags:
            validate: null
            ja: 性別
        phone_number:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,numeric,min=1,max=15'
            ja: 電話番号
        address:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 住所
        parent_name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 緊急連絡先氏名
        parent_cellphone_number:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,numeric,min=1,max=15'
            ja: 緊急連絡先携帯電話番号
        parent_homephone_number:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,numeric,min=1,max=15'
            ja: 緊急連絡先固定電話番号
        parent_address:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 緊急連絡先住所
    ResGetUserMePayment:
      required:
        - year
        - transfer_name
        - checked
        - updated_at
      properties:
        year:
          type: integer
        transfer_name:
          type: string
        checked:
          type: boolean
        updated_at:
          type: string
    ReqPutUserMePayment:
      required:
        - year
        - transfer_name
      properties:
        year:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,numeric'
            ja: 年度
        transfer_name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: 'required,min=1,max=255'
            ja: 振込名義
    Error:
      required:
        - level
        - message
      properties:
        level:
          type: string
        message:
          type: string
  responses:
    BadRequest:
      description: 'Validation error, etc.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: 'Authentication error, etc.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 'Resource does not exist, etc.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServer:
      description: 'System error, etc.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
