name: GitHub Pages


on:
  push:
    branches:
      - master


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy publish file
        run: |
          mkdir docs
          cp document/index.html docs/
          cp document/bundle.yml docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
